// @ts-nocheck
/* oxlint-disable */
// oxfmt-ignore
//
// AUTO-GENERATED by `cargo test -p uc-tauri --test specta_export`. DO NOT EDIT.
//
// Regenerate after changing any #[tauri::command], DTO, or error enum shape.
// CI rejects schema drift when this file is stale.
//
// 用户/校验类错误的 code 集合。前端中央 IPC 封装层据此判断某个 command
// 拒绝是否属于「用户操作错误」—— 是则不上报 Sentry(正常产品流程),
// 否则按系统错误上报。未列出的 code 默认按系统错误处理(fail-safe)。
//
// 权威来源:`src-tauri/crates/uc-tauri/src/commands/severity.rs`。

export const USER_FACING_ERROR_CODES: ReadonlySet<string> = new Set([
  "AccessibilityPermissionRequired",
  "Cancelled",
  "Conflict",
  "NotFound",
  "ValidationError",
]);
