package main

import (
	"fmt"
	"go/format"
	"strings"
)

const e2eTablePath = "apps/gui-go/e2e_invoke_table.go"

// renderE2ETable writes the command-name table the e2e control file's `invoke` verb uses. The control addresses a
// host command by its wire name with named JSON arguments (the shape every E2E script already sends); Go reflection
// has no parameter names, so they are read from the method declarations here and never kept by hand.
func renderE2ETable(commands []command) string {
	var b strings.Builder
	b.WriteString("//go:build e2e\n\n")
	b.WriteString("// Code generated by apps/gui-go/cmd/hostcontract; DO NOT EDIT.\n\n")
	b.WriteString("package main\n\n")
	b.WriteString("// e2eCommandTable maps a command's wire name to its HostService method and parameter names.\n")
	b.WriteString("var e2eCommandTable = map[string]e2eCommand{\n")
	for _, c := range commands {
		names := make([]string, len(c.Params))
		for i, p := range c.Params {
			names[i] = fmt.Sprintf("%q", p.Name)
		}
		fmt.Fprintf(&b, "\t%q: {Method: %q, Params: []string{%s}},\n", c.Wire, c.Method, strings.Join(names, ", "))
	}
	b.WriteString("}\n")
	out, err := format.Source([]byte(b.String()))
	if err != nil {
		fatal(err)
	}
	return string(out)
}
