package main

import (
	"fmt"
	"strings"

	"github.com/UniClipboard/UniClipboard/apps/gui-go/internal/hostapi"
)

const errorsTSHeader = `// Generated by apps/gui-go/cmd/hostcontract from apps/gui-go/internal/hostapi (the error catalog). Do not edit.
//
// Wails generates the command signatures and DTOs (apps/gui-go/frontend/bindings), but a bound Go method only
// returns ` + "`error`" + `, so the framework cannot describe which codes a command rejects with. The catalog in Go is the
// single source of those codes and of their severity; this file is its TypeScript form.
//
// User-facing rejections are normal product flow (wrong passphrase, cancelled dialog, bad input) and are never
// reported to Sentry. A token that is not listed is treated as a system error (fail safe toward visibility).
`

func quoted(infos []hostapi.CodeInfo) string {
	parts := make([]string, len(infos))
	for i, info := range infos {
		parts[i] = fmt.Sprintf("'%s'", info.Token)
	}
	return strings.Join(parts, ", ")
}

func userFacing(infos []hostapi.CodeInfo) []string {
	var out []string
	for _, info := range infos {
		if info.Severity == hostapi.UserFacing {
			out = append(out, fmt.Sprintf("'%s'", info.Token))
		}
	}
	return out
}

// renderErrorsTS writes the frontend form of the error catalog.
func renderErrorsTS() string {
	c := hostapi.Catalog
	var b strings.Builder
	b.WriteString(errorsTSHeader)
	b.WriteString("\n")
	fmt.Fprintf(&b, "export const COMMAND_ERROR_CODES = [%s] as const\n", quoted(c.Command))
	b.WriteString("export type CommandErrorCode = (typeof COMMAND_ERROR_CODES)[number]\n")
	b.WriteString("/** Rejection of most commands. */\n")
	b.WriteString("export type CommandError = { code: CommandErrorCode; message: string }\n\n")
	fmt.Fprintf(&b, "export const UNLOCK_ERROR_CODES = [%s] as const\n", quoted(c.Unlock))
	b.WriteString("export type ContentUnlockErrorCode = (typeof UNLOCK_ERROR_CODES)[number]\n")
	b.WriteString("/** Rejection of unlock_content: only the stable code crosses the bridge. */\n")
	b.WriteString("export type ContentUnlockError = { code: ContentUnlockErrorCode }\n\n")
	fmt.Fprintf(&b, "export const CONFIG_ERROR_KINDS = [%s] as const\n", quoted(c.Config))
	b.WriteString("export type ConfigCommandErrorKind = (typeof CONFIG_ERROR_KINDS)[number]\n")
	b.WriteString("/** Rejection of the config package commands, told apart by `kind`. */\n")
	b.WriteString("export type ConfigCommandError =\n")
	b.WriteString("  | { kind: 'cancelled' }\n")
	b.WriteString("  | { kind: 'daemon'; status: number; code: string | null; message: string }\n")
	b.WriteString("  | { kind: 'internal'; message: string }\n\n")
	b.WriteString("/** Update, quick panel and window commands reject with a plain string and have no code. */\n")
	b.WriteString("export type TextCommandError = string\n\n")
	b.WriteString("export const USER_FACING_ERROR_CODES: ReadonlySet<string> = new Set([\n")
	for _, token := range append(userFacing(c.Command), userFacing(c.Unlock)...) {
		fmt.Fprintf(&b, "  %s,\n", token)
	}
	b.WriteString("])\n\n")
	b.WriteString("export const USER_FACING_ERROR_KINDS: ReadonlySet<string> = new Set([\n")
	for _, token := range userFacing(c.Config) {
		fmt.Fprintf(&b, "  %s,\n", token)
	}
	b.WriteString("])\n")
	return b.String()
}
