//go:build ignore

// gen.go regenerates buildinfo.go from the Rust workspace, which stays the
// single source of truth for the package version and daemon API revision.
//
//	go generate ./buildinfo
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
)

func main() {
	root := filepath.Join("..", "..", "..")
	cargo := mustRead(filepath.Join(root, "Cargo.toml"))
	contract := mustRead(filepath.Join(root, "crates", "uc-daemon-contract", "src", "lib.rs"))

	version := mustMatch(`(?m)^\[workspace\.package\][^\[]*?^version\s*=\s*"([^"]+)"`, cargo, "workspace package version")
	revision := mustMatch(`DAEMON_API_REVISION:\s*&str\s*=\s*"([^"]+)"`, contract, "DAEMON_API_REVISION")

	out := fmt.Sprintf(`// Code generated by gen.go from Cargo.toml and uc-daemon-contract; DO NOT EDIT.

package buildinfo

// PackageVersion is the workspace package version the daemon must report.
const PackageVersion = %q

// DaemonAPIRevision is the daemon contract revision the daemon must report.
const DaemonAPIRevision = %q
`, version, revision)
	if err := os.WriteFile("buildinfo.go", []byte(out), 0o644); err != nil {
		panic(err)
	}
}

func mustRead(path string) string {
	data, err := os.ReadFile(path)
	if err != nil {
		panic(err)
	}
	return string(data)
}

func mustMatch(pattern, text, what string) string {
	m := regexp.MustCompile(pattern).FindStringSubmatch(text)
	if m == nil {
		panic("cannot find " + what)
	}
	return m[1]
}
