// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Session is the short-lived browser credential returned by the daemon.
 */
export interface Session {
    "sessionToken": string;
    "expiresInSecs": number;
    "refreshAtSecs": number;
}
