use super::{Count, Dates, Platform, Service, Text};

pub(super) static TEXT: Text = Text {
    search_placeholder: "Search, or type # tag  @ device  / type",
    actions: "Actions",
    send_to: "Send to",
    actions_hint: "↑↓ select · ⏎ run · esc back",
    nothing_to_open: "This entry has no link or file to open.",
    no_log_dir: "Log folder not found.",
    first_use_title: "No clipboard history yet",
    first_use_hint: "Anything you copy on any of your devices shows up here.",
    summon_anytime: "Open anytime with",
    locked_title: "The app is locked",
    unlock: "Unlock",
    disconnected_title: "The sync service is not responding",
    reconnect_hint: "The list refreshes by itself once it is back.",
    reconnect_now: "Reconnect now",
    view_logs: "View logs",
    close: "Close",
    try_relaxing: "Try loosening:",
    apply_suggestion: "Apply suggestion",
    clear: "Clear",
    needs_app: "This only works inside the UniClipboard app.",
    host_gone: "Cannot reach the main app.",
    locked_hint_gui:
        "Enter your passphrase in the main window to unlock; this refreshes by itself.",
    open_main_window: "Open main window",
    settings: "Settings…",
    suggestions: "Suggestions",
    accept_in_order: "accept in order",
    press_again: "press",
    all_types: "All",
    try_other_terms: "Try different keywords or filters",
    searching: "Searching…",
    just_now: "Just now",
    loading: "Loading…",
    loading_image: "Loading image…",
    retry: "Retry",
    fit_to_window: "Fit",
    actual_size: "Actual size",
    delete_hint_mac: "⌘⇧⌫ delete",
    delete_hint_other: "Ctrl+Shift+⌫ delete",
    shortcut_taken: "Cannot register the shortcut; another app may be using it.",
    preview_window_failed: "Cannot open the preview window.",
    copy: "Copy",
    hidden_count: "{n} more",
    reconnecting: "Reconnecting automatically (attempt {n}).",
    no_match: "Nothing matches these filters",
    no_match_query: "Nothing matches “{query}”",
    paste: "Paste",
    paste_to: "Paste to {name}",
    result_count: Count {
        one: "{n} result",
        few: "{n} results",
        other: "{n} results",
    },
    text_match_count: Count {
        one: "{n} text match",
        few: "{n} text matches",
        other: "{n} text matches",
    },
    text_matches: "Text matches",
    dimension_type: "Type",
    dimension_tag: "Tag",
    dimension_source: "Device",
    dimension_time: "Time",
    kind_text: "Text",
    kind_rich_text: "Rich Text",
    kind_image: "Image",
    kind_file: "File",
    kind_link: "Link",
    kind_code: "Code",
    kind_directory: "Folder",
    tag_favorited: "Favorites",
    paste_plain: "Paste as plain text",
    paste_keep_open: "Paste and keep panel open",
    copy_only: "Copy only",
    paste_paths: "Paste file paths",
    open: "Open",
    reveal_file: "Show in folder",
    send_to_device: "Send to device",
    favorite: "Favorite",
    unfavorite: "Unfavorite",
    delete: "Delete",
    all_devices: "All devices",
    lines: Count {
        one: "{n} line",
        few: "{n} lines",
        other: "{n} lines",
    },
    characters: Count {
        one: "{n} character",
        few: "{n} characters",
        other: "{n} characters",
    },
    items: Count {
        one: "{n} item",
        few: "{n} items",
        other: "{n} items",
    },
    from_device: "from {name}",
    remove_type: "Remove /{value}",
    remove_all_types: "Remove all types",
    remove_tag: "Remove #{value}",
    remove_all_tags: "Remove all tags",
    widen_time: "Search all time",
    remove_device: "Remove @{name} and include all devices",
    include_all_devices: "Include all devices",
    dates: Dates {
        today: "Today",
        yesterday: "Yesterday",
        day_before_yesterday: "2 days ago",
        this_week: "This week",
        last_week: "Last week",
        this_month: "This month",
        last_month: "Last month",
        last_days: Count {
            one: "Last {n} day",
            few: "Last {n} days",
            other: "Last {n} days",
        },
        months: [
            "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
        ],
        day: "{month} {d}",
        day_with_year: "{month} {d}, {y}",
        end_day_same_month: "{d}",
        month: "{month}",
        month_with_year: "{month} {y}",
        since: "Since {date}",
        until: "Until {date}",
    },
    platform: Platform {
        unsupported: "Not supported on this platform yet.",
        panel_window_inaccessible: "Cannot access the panel window.",
        preview_window_inaccessible: "Cannot access the preview window.",
        unsupported_window_kind: "Unsupported window type.",
        panel_window_closed: "The panel window is closed.",
        preview_window_closed: "The preview window is closed.",
        preview_layer_not_ready: "The preview is not ready to draw yet.",
        main_thread_required: "Must run on the main thread.",
        no_display: "No display found.",
        invalid_link: "Invalid link.",
        cannot_open: "Cannot open this item.",
        no_paste_permission:
            "Pasting automatically needs Accessibility permission; you can use Copy instead.",
        no_paste_target: "No app to paste into; open the panel from another app.",
        paste_target_quit: "The app has quit; open the panel again.",
        focus_moved: "Focus moved; go back to the app and open the panel again.",
        cannot_return_to_target: "Cannot switch back to the app; open the panel again.",
        paste_target_missing: "No app to paste into.",
        cannot_create_typing_event: "Cannot create the typing event.",
        cannot_create_paste_event: "Cannot create the paste event.",
    },
    service: Service {
        locked: "The clipboard is locked; unlock it to continue.",
        search_failed: "Search failed; try again.",
        disconnected: "The sync service is not responding.",
        interrupted: "The request was interrupted; try again.",
        search_timeout: "Search timed out; try again.",
        not_running: "Cannot reach UniClipboard; start and unlock the desktop app first.",
        cannot_connect: "Cannot connect to the background service.",
        restore_failed: "Cannot copy this entry; refresh and try again.",
        restore_timeout: "Copying timed out; try again.",
        action_failed: "The action failed; try again.",
        tags_unavailable: "Cannot load tags.",
        devices_unavailable: "Cannot load devices.",
        preview_timeout: "The preview took too long to load.",
        preview_unreadable: "Cannot read the preview.",
        entry_gone: "This content is no longer available.",
        image_unreadable: "Cannot read the image.",
        image_gone: "The image is no longer available.",
        image_bad_format: "The image data is malformed.",
        image_unsupported: "Unsupported image format.",
        image_undecodable: "The image cannot be decoded.",
        copy_failed: "Copy failed; try again.",
        no_paths: "No file paths to paste.",
        preview_unreadable_retry: "Cannot read the preview; try again.",
    },
};
