use super::{Count, Dates, Platform, Service, Text};

pub(super) static TEXT: Text = Text {
    search_placeholder: "検索、または # タグ  @ デバイス  / タイプ",
    actions: "操作",
    send_to: "送信先",
    actions_hint: "↑↓ 選択 · ⏎ 実行 · esc 戻る",
    nothing_to_open: "この項目には開けるリンクやファイルがありません。",
    no_log_dir: "ログフォルダが見つかりません。",
    first_use_title: "クリップボード履歴はまだありません",
    first_use_hint: "どのデバイスでコピーした内容もここに表示されます。",
    summon_anytime: "いつでも呼び出す",
    locked_title: "アプリはロックされています",
    unlock: "ロック解除",
    disconnected_title: "同期サービスが応答しません",
    reconnect_hint: "復旧するとリストは自動で更新されます。",
    reconnect_now: "今すぐ再接続",
    view_logs: "ログを表示",
    close: "閉じる",
    try_relaxing: "条件を緩める：",
    apply_suggestion: "提案を適用",
    clear: "クリア",
    needs_app: "この機能は UniClipboard アプリ内でのみ使用できます。",
    host_gone: "メインアプリに接続できません。",
    locked_hint_gui:
        "メイン画面でパスフレーズを入力してロックを解除すると、ここは自動で更新されます。",
    open_main_window: "メイン画面を開く",
    settings: "設定…",
    suggestions: "提案",
    accept_in_order: "順に確定",
    press_again: "もう一度",
    all_types: "すべて",
    try_other_terms: "別のキーワードまたはフィルタを試してください",
    searching: "検索中…",
    just_now: "今",
    loading: "読み込み中…",
    loading_image: "画像を読み込み中…",
    retry: "再試行",
    fit_to_window: "全体表示",
    actual_size: "実際のサイズ",
    delete_hint_mac: "⌘⇧⌫ 削除",
    delete_hint_other: "Ctrl+Shift+⌫ 削除",
    shortcut_taken: "ショートカットを登録できません。他のアプリが使用している可能性があります。",
    preview_window_failed: "プレビューウィンドウを開けません。",
    copy: "コピー",
    hidden_count: "他 {n} 件",
    reconnecting: "自動で再接続しています（{n} 回目）。",
    no_match: "条件に一致する項目はありません",
    no_match_query: "「{query}」に一致する項目はありません",
    paste: "貼り付け",
    paste_to: "{name} に貼り付け",
    result_count: Count::same("{n} 件"),
    text_match_count: Count::same("テキスト一致 {n} 件"),
    text_matches: "テキスト一致",
    dimension_type: "タイプ",
    dimension_tag: "タグ",
    dimension_source: "デバイス",
    dimension_time: "時間",
    kind_text: "テキスト",
    kind_rich_text: "リッチテキスト",
    kind_image: "画像",
    kind_file: "ファイル",
    kind_link: "リンク",
    kind_code: "コード",
    kind_directory: "フォルダ",
    tag_favorited: "お気に入り",
    paste_plain: "プレーンテキストで貼り付け",
    paste_keep_open: "貼り付けてパネルを開いたままにする",
    copy_only: "コピーのみ",
    paste_paths: "ファイルパスを貼り付け",
    open: "開く",
    reveal_file: "フォルダに表示",
    send_to_device: "デバイスに送信",
    favorite: "お気に入り",
    unfavorite: "お気に入り解除",
    delete: "削除",
    all_devices: "すべてのデバイス",
    lines: Count::same("{n} 行"),
    characters: Count::same("{n} 文字"),
    items: Count::same("{n} 項目"),
    from_device: "{name} から",
    remove_type: "/{value} を外す",
    remove_all_types: "すべてのタイプを外す",
    remove_tag: "#{value} を外す",
    remove_all_tags: "すべてのタグを外す",
    widen_time: "期間をすべてに広げる",
    remove_device: "@{name} を外してすべてのデバイスを含める",
    include_all_devices: "すべてのデバイスを含める",
    dates: Dates {
        today: "今日",
        yesterday: "昨日",
        day_before_yesterday: "一昨日",
        this_week: "今週",
        last_week: "先週",
        this_month: "今月",
        last_month: "先月",
        last_days: Count::same("過去 {n} 日間"),
        months: [
            "1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月",
        ],
        day: "{m}月{d}日",
        day_with_year: "{y}年{m}月{d}日",
        end_day_same_month: "{d}日",
        month: "{m}月",
        month_with_year: "{y}年{m}月",
        since: "{date}以降",
        until: "{date}まで",
    },
    platform: Platform {
        unsupported: "このプラットフォームではまだサポートされていません。",
        panel_window_inaccessible: "パネルウィンドウにアクセスできません。",
        preview_window_inaccessible: "プレビューウィンドウにアクセスできません。",
        unsupported_window_kind: "サポートされていないウィンドウの種類です。",
        panel_window_closed: "パネルウィンドウは閉じられています。",
        preview_window_closed: "プレビューウィンドウは閉じられています。",
        preview_layer_not_ready: "プレビューの描画準備ができていません。",
        main_thread_required: "メインスレッドで実行する必要があります。",
        no_display: "ディスプレイが見つかりません。",
        invalid_link: "無効なリンクです。",
        cannot_open: "この項目を開けません。",
        no_paste_permission:
            "自動貼り付けにはアクセシビリティの許可が必要です。代わりにコピーを使用できます。",
        no_paste_target: "貼り付け先のアプリがありません。他のアプリからパネルを開いてください。",
        paste_target_quit: "元のアプリは終了しました。パネルをもう一度開いてください。",
        focus_moved: "フォーカスが移動しました。対象のアプリに戻ってパネルを開き直してください。",
        cannot_return_to_target: "対象のアプリに戻れません。パネルをもう一度開いてください。",
        paste_target_missing: "貼り付け先のアプリがありません。",
        cannot_create_typing_event: "入力イベントを作成できません。",
        cannot_create_paste_event: "貼り付けイベントを作成できません。",
    },
    service: Service {
        locked: "クリップボードはロックされています。ロックを解除して続行してください。",
        search_failed: "検索に失敗しました。もう一度お試しください。",
        disconnected: "同期サービスが応答しません。",
        interrupted: "リクエストが中断されました。もう一度お試しください。",
        search_timeout: "検索がタイムアウトしました。もう一度お試しください。",
        not_running:
            "UniClipboard に接続できません。デスクトップアプリを起動してロックを解除してください。",
        cannot_connect: "バックグラウンド接続を作成できません。",
        restore_failed: "この項目をコピーできません。更新してもう一度お試しください。",
        restore_timeout: "コピーがタイムアウトしました。もう一度お試しください。",
        action_failed: "操作に失敗しました。もう一度お試しください。",
        tags_unavailable: "タグを読み込めません。",
        devices_unavailable: "デバイスを読み込めません。",
        preview_timeout: "プレビューの読み込みがタイムアウトしました。",
        preview_unreadable: "プレビューを読み込めません。",
        entry_gone: "この内容は利用できなくなりました。",
        image_unreadable: "画像を読み込めません。",
        image_gone: "画像は利用できなくなりました。",
        image_bad_format: "画像の形式が正しくありません。",
        image_unsupported: "サポートされていない画像形式です。",
        image_undecodable: "画像をデコードできません。",
        copy_failed: "コピーに失敗しました。もう一度お試しください。",
        no_paths: "貼り付けるファイルパスがありません。",
        preview_unreadable_retry: "プレビューを読み込めません。もう一度お試しください。",
    },
};
