use super::{Count, Dates, Platform, Service, Text};

pub(super) static TEXT: Text = Text {
    search_placeholder: "Pesquise, ou digite # tag  @ dispositivo  / tipo",
    actions: "Ações",
    send_to: "Enviar para",
    actions_hint: "↑↓ selecionar · ⏎ executar · esc voltar",
    nothing_to_open: "Este item não tem link nem arquivo para abrir.",
    no_log_dir: "Pasta de logs não encontrada.",
    first_use_title: "Ainda não há histórico da área de transferência",
    first_use_hint: "Tudo o que você copiar em qualquer dispositivo aparece aqui.",
    summon_anytime: "Abra a qualquer momento com",
    locked_title: "O app está bloqueado",
    unlock: "Desbloquear",
    disconnected_title: "O serviço de sincronização não está respondendo",
    reconnect_hint: "A lista se atualiza sozinha quando ele voltar.",
    reconnect_now: "Reconectar agora",
    view_logs: "Ver logs",
    close: "Fechar",
    try_relaxing: "Tente afrouxar:",
    apply_suggestion: "Aplicar sugestão",
    clear: "Limpar",
    needs_app: "Isto só funciona dentro do app UniClipboard.",
    host_gone: "Não foi possível contatar o app principal.",
    locked_hint_gui:
        "Digite sua frase secreta na janela principal para desbloquear; isto se atualiza sozinho.",
    open_main_window: "Abrir janela principal",
    settings: "Configurações…",
    suggestions: "Sugestões",
    accept_in_order: "aceitar em ordem",
    press_again: "pressione",
    all_types: "Todos",
    try_other_terms: "Tente outras palavras-chave ou filtros",
    searching: "Pesquisando…",
    just_now: "Agora mesmo",
    loading: "Carregando…",
    loading_image: "Carregando imagem…",
    retry: "Tentar novamente",
    fit_to_window: "Ajustar",
    actual_size: "Tamanho real",
    delete_hint_mac: "⌘⇧⌫ excluir",
    delete_hint_other: "Ctrl+Shift+⌫ excluir",
    shortcut_taken: "Não foi possível registrar o atalho; outro app pode estar usando-o.",
    preview_window_failed: "Não foi possível abrir a janela de pré-visualização.",
    copy: "Copiar",
    hidden_count: "Mais {n}",
    reconnecting: "Reconectando automaticamente (tentativa {n}).",
    no_match: "Nada corresponde a estes filtros",
    no_match_query: "Nada corresponde a “{query}”",
    paste: "Colar",
    paste_to: "Colar em {name}",
    result_count: Count {
        one: "{n} resultado",
        few: "{n} resultados",
        other: "{n} resultados",
    },
    text_match_count: Count {
        one: "{n} correspondência de texto",
        few: "{n} correspondências de texto",
        other: "{n} correspondências de texto",
    },
    text_matches: "Correspondências de texto",
    dimension_type: "Tipo",
    dimension_tag: "Tag",
    dimension_source: "Dispositivo",
    dimension_time: "Período",
    kind_text: "Texto",
    kind_rich_text: "Texto formatado",
    kind_image: "Imagem",
    kind_file: "Arquivo",
    kind_link: "Link",
    kind_code: "Código",
    kind_directory: "Pasta",
    tag_favorited: "Favoritos",
    paste_plain: "Colar como texto simples",
    paste_keep_open: "Colar e manter o painel aberto",
    copy_only: "Apenas copiar",
    paste_paths: "Colar caminhos dos arquivos",
    open: "Abrir",
    reveal_file: "Mostrar na pasta",
    send_to_device: "Enviar para dispositivo",
    favorite: "Favoritar",
    unfavorite: "Desfavoritar",
    delete: "Excluir",
    all_devices: "Todos os dispositivos",
    lines: Count {
        one: "{n} linha",
        few: "{n} linhas",
        other: "{n} linhas",
    },
    characters: Count {
        one: "{n} caractere",
        few: "{n} caracteres",
        other: "{n} caracteres",
    },
    items: Count {
        one: "{n} item",
        few: "{n} itens",
        other: "{n} itens",
    },
    from_device: "de {name}",
    remove_type: "Remover /{value}",
    remove_all_types: "Remover todos os tipos",
    remove_tag: "Remover #{value}",
    remove_all_tags: "Remover todas as tags",
    widen_time: "Pesquisar em todo o período",
    remove_device: "Remover @{name} e incluir todos os dispositivos",
    include_all_devices: "Incluir todos os dispositivos",
    dates: Dates {
        today: "Hoje",
        yesterday: "Ontem",
        day_before_yesterday: "Anteontem",
        this_week: "Esta semana",
        last_week: "Semana passada",
        this_month: "Este mês",
        last_month: "Mês passado",
        last_days: Count {
            one: "Último {n} dia",
            few: "Últimos {n} dias",
            other: "Últimos {n} dias",
        },
        months: [
            "janeiro",
            "fevereiro",
            "março",
            "abril",
            "maio",
            "junho",
            "julho",
            "agosto",
            "setembro",
            "outubro",
            "novembro",
            "dezembro",
        ],
        day: "{dd}/{mm}",
        day_with_year: "{dd}/{mm}/{y}",
        end_day_same_month: "{dd}/{mm}",
        month: "{month}",
        month_with_year: "{month} de {y}",
        since: "Desde {date}",
        until: "Até {date}",
    },
    platform: Platform {
        unsupported: "Ainda não é compatível com esta plataforma.",
        panel_window_inaccessible: "Não foi possível acessar a janela do painel.",
        preview_window_inaccessible: "Não foi possível acessar a janela de pré-visualização.",
        unsupported_window_kind: "Tipo de janela não compatível.",
        panel_window_closed: "A janela do painel está fechada.",
        preview_window_closed: "A janela de pré-visualização está fechada.",
        preview_layer_not_ready: "A pré-visualização ainda não está pronta.",
        main_thread_required: "Precisa ser executado na thread principal.",
        no_display: "Nenhuma tela encontrada.",
        invalid_link: "Link inválido.",
        cannot_open: "Não foi possível abrir este item.",
        no_paste_permission:
            "Colar automaticamente exige permissão de Acessibilidade; você pode usar Copiar.",
        no_paste_target: "Não há app para colar; abra o painel a partir de outro app.",
        paste_target_quit: "O app foi encerrado; abra o painel novamente.",
        focus_moved: "O foco mudou; volte ao app e abra o painel novamente.",
        cannot_return_to_target: "Não foi possível voltar ao app; abra o painel novamente.",
        paste_target_missing: "Não há app para colar.",
        cannot_create_typing_event: "Não foi possível criar o evento de digitação.",
        cannot_create_paste_event: "Não foi possível criar o evento de colar.",
    },
    service: Service {
        locked: "A área de transferência está bloqueada; desbloqueie para continuar.",
        search_failed: "A pesquisa falhou; tente novamente.",
        disconnected: "O serviço de sincronização não está respondendo.",
        interrupted: "A solicitação foi interrompida; tente novamente.",
        search_timeout: "A pesquisa expirou; tente novamente.",
        not_running:
            "Não foi possível conectar ao UniClipboard; abra e desbloqueie o app primeiro.",
        cannot_connect: "Não foi possível conectar ao serviço em segundo plano.",
        restore_failed: "Não foi possível copiar este item; atualize e tente novamente.",
        restore_timeout: "A cópia expirou; tente novamente.",
        action_failed: "A ação falhou; tente novamente.",
        tags_unavailable: "Não foi possível carregar as tags.",
        devices_unavailable: "Não foi possível carregar os dispositivos.",
        preview_timeout: "A pré-visualização demorou demais para carregar.",
        preview_unreadable: "Não foi possível ler a pré-visualização.",
        entry_gone: "Este conteúdo não está mais disponível.",
        image_unreadable: "Não foi possível ler a imagem.",
        image_gone: "A imagem não está mais disponível.",
        image_bad_format: "Os dados da imagem estão corrompidos.",
        image_unsupported: "Formato de imagem não compatível.",
        image_undecodable: "Não foi possível decodificar a imagem.",
        copy_failed: "A cópia falhou; tente novamente.",
        no_paths: "Não há caminhos de arquivo para colar.",
        preview_unreadable_retry: "Não foi possível ler a pré-visualização; tente novamente.",
    },
};
