use super::{Count, Dates, Platform, Service, Text};

pub(super) static TEXT: Text = Text {
    search_placeholder: "Поиск, или # тег  @ устройство  / тип",
    actions: "Действия",
    send_to: "Отправить на",
    actions_hint: "↑↓ выбор · ⏎ выполнить · esc назад",
    nothing_to_open: "В этой записи нет ссылки или файла, которые можно открыть.",
    no_log_dir: "Папка журналов не найдена.",
    first_use_title: "История буфера обмена пока пуста",
    first_use_hint: "Всё, что вы копируете на любом устройстве, появится здесь.",
    summon_anytime: "Открыть в любой момент:",
    locked_title: "Приложение заблокировано",
    unlock: "Разблокировать",
    disconnected_title: "Служба синхронизации не отвечает",
    reconnect_hint: "Список обновится сам, как только связь восстановится.",
    reconnect_now: "Переподключить",
    view_logs: "Открыть журналы",
    close: "Закрыть",
    try_relaxing: "Попробуйте ослабить условия:",
    apply_suggestion: "Применить",
    clear: "Очистить",
    needs_app: "Эта функция работает только в приложении UniClipboard.",
    host_gone: "Не удаётся связаться с основным приложением.",
    locked_hint_gui: "Введите парольную фразу в главном окне; после разблокировки здесь всё обновится само.",
    open_main_window: "Открыть главное окно",
    settings: "Настройки…",
    suggestions: "Подсказки",
    accept_in_order: "принимать по порядку",
    press_again: "нажмите",
    all_types: "Все",
    try_other_terms: "Попробуйте другие ключевые слова или фильтры",
    searching: "Поиск…",
    just_now: "Только что",
    loading: "Загрузка…",
    loading_image: "Загрузка изображения…",
    retry: "Повторить",
    fit_to_window: "Целиком",
    actual_size: "Исходный размер",
    delete_hint_mac: "⌘⇧⌫ удалить",
    delete_hint_other: "Ctrl+Shift+⌫ удалить",
    shortcut_taken: "Не удалось назначить сочетание клавиш; возможно, оно занято другой программой.",
    preview_window_failed: "Не удалось открыть окно предпросмотра.",
    copy: "Копировать",
    hidden_count: "Ещё: {n}",
    reconnecting: "Автоматическое переподключение (попытка {n}).",
    no_match: "Ничего не найдено по этим условиям",
    no_match_query: "Ничего не найдено по запросу «{query}»",
    paste: "Вставить",
    paste_to: "Вставить в {name}",
    result_count: Count {
        one: "{n} результат",
        few: "{n} результата",
        other: "{n} результатов",
    },
    text_match_count: Count {
        one: "{n} совпадение по тексту",
        few: "{n} совпадения по тексту",
        other: "{n} совпадений по тексту",
    },
    text_matches: "Совпадения по тексту",
    dimension_type: "Тип",
    dimension_tag: "Тег",
    dimension_source: "Устройство",
    dimension_time: "Время",
    kind_text: "Текст",
    kind_rich_text: "Форматированный текст",
    kind_image: "Изображение",
    kind_file: "Файл",
    kind_link: "Ссылка",
    kind_code: "Код",
    kind_directory: "Папка",
    tag_favorited: "Избранное",
    paste_plain: "Вставить как обычный текст",
    paste_keep_open: "Вставить, не закрывая панель",
    copy_only: "Только копировать",
    paste_paths: "Вставить пути к файлам",
    open: "Открыть",
    reveal_file: "Показать в папке",
    send_to_device: "Отправить на устройство",
    favorite: "В избранное",
    unfavorite: "Убрать из избранного",
    delete: "Удалить",
    all_devices: "Все устройства",
    lines: Count {
        one: "{n} строка",
        few: "{n} строки",
        other: "{n} строк",
    },
    characters: Count {
        one: "{n} символ",
        few: "{n} символа",
        other: "{n} символов",
    },
    items: Count {
        one: "{n} элемент",
        few: "{n} элемента",
        other: "{n} элементов",
    },
    from_device: "с {name}",
    remove_type: "Убрать /{value}",
    remove_all_types: "Убрать все типы",
    remove_tag: "Убрать #{value}",
    remove_all_tags: "Убрать все теги",
    widen_time: "Искать за всё время",
    remove_device: "Убрать @{name} и включить все устройства",
    include_all_devices: "Включить все устройства",
    dates: Dates {
        today: "Сегодня",
        yesterday: "Вчера",
        day_before_yesterday: "Позавчера",
        this_week: "На этой неделе",
        last_week: "На прошлой неделе",
        this_month: "В этом месяце",
        last_month: "В прошлом месяце",
        last_days: Count {
            one: "Последний {n} день",
            few: "Последние {n} дня",
            other: "Последние {n} дней",
        },
        months: [
            "январь",
            "февраль",
            "март",
            "апрель",
            "май",
            "июнь",
            "июль",
            "август",
            "сентябрь",
            "октябрь",
            "ноябрь",
            "декабрь",
        ],
        day: "{dd}.{mm}",
        day_with_year: "{dd}.{mm}.{y}",
        end_day_same_month: "{dd}.{mm}",
        month: "{month}",
        month_with_year: "{month} {y}",
        since: "С {date}",
        until: "По {date}",
    },
    platform: Platform {
        unsupported: "На этой платформе пока не поддерживается.",
        panel_window_inaccessible: "Нет доступа к окну панели.",
        preview_window_inaccessible: "Нет доступа к окну предпросмотра.",
        unsupported_window_kind: "Неподдерживаемый тип окна.",
        panel_window_closed: "Окно панели закрыто.",
        preview_window_closed: "Окно предпросмотра закрыто.",
        preview_layer_not_ready: "Предпросмотр ещё не готов к отрисовке.",
        main_thread_required: "Требуется главный поток.",
        no_display: "Дисплей не найден.",
        invalid_link: "Недопустимая ссылка.",
        cannot_open: "Не удалось открыть этот элемент.",
        no_paste_permission:
            "Для автоматической вставки нужно разрешение универсального доступа; можно использовать копирование.",
        no_paste_target: "Некуда вставлять; откройте панель из другого приложения.",
        paste_target_quit: "Приложение закрыто; откройте панель снова.",
        focus_moved: "Фокус сменился; вернитесь в приложение и откройте панель снова.",
        cannot_return_to_target: "Не удалось вернуться в приложение; откройте панель снова.",
        paste_target_missing: "Некуда вставлять.",
        cannot_create_typing_event: "Не удалось создать событие ввода.",
        cannot_create_paste_event: "Не удалось создать событие вставки.",
    },
    service: Service {
        locked: "Буфер обмена заблокирован; разблокируйте его, чтобы продолжить.",
        search_failed: "Поиск не удался; повторите попытку.",
        disconnected: "Служба синхронизации не отвечает.",
        interrupted: "Запрос прерван; повторите попытку.",
        search_timeout: "Время поиска истекло; повторите попытку.",
        not_running: "Не удаётся подключиться к UniClipboard; сначала запустите и разблокируйте приложение.",
        cannot_connect: "Не удалось подключиться к фоновой службе.",
        restore_failed: "Не удалось скопировать запись; обновите и повторите попытку.",
        restore_timeout: "Время копирования истекло; повторите попытку.",
        action_failed: "Действие не выполнено; повторите попытку.",
        tags_unavailable: "Не удалось загрузить теги.",
        devices_unavailable: "Не удалось загрузить устройства.",
        preview_timeout: "Предпросмотр загружается слишком долго.",
        preview_unreadable: "Не удалось прочитать предпросмотр.",
        entry_gone: "Это содержимое больше недоступно.",
        image_unreadable: "Не удалось прочитать изображение.",
        image_gone: "Изображение больше недоступно.",
        image_bad_format: "Данные изображения повреждены.",
        image_unsupported: "Неподдерживаемый формат изображения.",
        image_undecodable: "Не удалось декодировать изображение.",
        copy_failed: "Не удалось скопировать; повторите попытку.",
        no_paths: "Нет путей к файлам для вставки.",
        preview_unreadable_retry: "Не удалось прочитать предпросмотр; повторите попытку.",
    },
};
