use super::{Count, Dates, Platform, Service, Text};

pub(super) static TEXT: Text = Text {
    search_placeholder: "搜索，或输入 # 标签  @ 设备  / 类型",
    actions: "操作",
    send_to: "发送到",
    actions_hint: "↑↓ 选择 · ⏎ 执行 · esc 返回",
    nothing_to_open: "这条记录没有可打开的链接或文件。",
    no_log_dir: "找不到日志目录。",
    first_use_title: "还没有剪贴板历史",
    first_use_hint: "在任意设备上复制内容，都会出现在这里。",
    summon_anytime: "随时唤起",
    locked_title: "应用界面已锁定",
    unlock: "解锁",
    disconnected_title: "同步服务未响应",
    reconnect_hint: "本次唤起期间恢复会自动刷新列表。",
    reconnect_now: "立即重连",
    view_logs: "查看日志",
    close: "关闭",
    try_relaxing: "试试放宽：",
    apply_suggestion: "应用建议",
    clear: "清空",
    needs_app: "此功能需要在 UniClipboard 应用内使用。",
    host_gone: "无法联系主程序。",
    locked_hint_gui: "在主窗口输入口令解锁，解锁后这里会自动刷新。",
    open_main_window: "打开主窗口",
    settings: "设置…",
    suggestions: "建议",
    accept_in_order: "按顺序接受",
    press_again: "再按",
    all_types: "全部",
    try_other_terms: "试试其他关键词或筛选条件",
    searching: "正在搜索…",
    just_now: "刚刚",
    loading: "正在加载…",
    loading_image: "正在加载图片…",
    retry: "重试",
    fit_to_window: "完整显示",
    actual_size: "原始尺寸",
    delete_hint_mac: "⌘⇧⌫ 删除",
    delete_hint_other: "Ctrl+Shift+⌫ 删除",
    shortcut_taken: "无法注册快捷键，可能已被其他程序占用。",
    preview_window_failed: "无法打开预览窗口。",
    copy: "复制",
    hidden_count: "还有 {n} 条",
    reconnecting: "正在自动重连（第 {n} 次）。",
    no_match: "没有符合条件的内容",
    no_match_query: "没有匹配“{query}”的内容",
    paste: "粘贴",
    paste_to: "粘贴到 {name}",
    result_count: Count::same("{n} 条"),
    text_match_count: Count::same("{n} 条文字匹配"),
    text_matches: "文字匹配",
    dimension_type: "类型",
    dimension_tag: "标签",
    dimension_source: "设备",
    dimension_time: "时间",
    kind_text: "文本",
    kind_rich_text: "富文本",
    kind_image: "图片",
    kind_file: "文件",
    kind_link: "链接",
    kind_code: "代码",
    kind_directory: "文件夹",
    tag_favorited: "收藏",
    paste_plain: "粘贴为纯文本",
    paste_keep_open: "粘贴并保持面板",
    copy_only: "只复制",
    paste_paths: "粘贴文件路径",
    open: "打开",
    reveal_file: "在文件夹中显示",
    send_to_device: "发送到设备",
    favorite: "收藏",
    unfavorite: "取消收藏",
    delete: "删除",
    all_devices: "所有设备",
    lines: Count::same("{n} 行"),
    characters: Count::same("{n} 个字符"),
    items: Count::same("{n} 项"),
    from_device: "来自 {name}",
    remove_type: "去掉 /{value}",
    remove_all_types: "去掉所有类型",
    remove_tag: "去掉 #{value}",
    remove_all_tags: "去掉所有标签",
    widen_time: "时间范围扩大到全部",
    remove_device: "去掉 @{name}，包含所有设备",
    include_all_devices: "包含所有设备",
    dates: Dates {
        today: "今天",
        yesterday: "昨天",
        day_before_yesterday: "前天",
        this_week: "本周",
        last_week: "上周",
        this_month: "本月",
        last_month: "上月",
        last_days: Count::same("最近{n}天"),
        months: [
            "1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月",
        ],
        day: "{m}月{d}日",
        day_with_year: "{y}年{m}月{d}日",
        end_day_same_month: "{d}日",
        month: "{m}月",
        month_with_year: "{y}年{m}月",
        since: "{date}起",
        until: "{date}前",
    },
    platform: Platform {
        unsupported: "此平台暂不支持该功能。",
        panel_window_inaccessible: "无法访问面板窗口。",
        preview_window_inaccessible: "无法访问预览窗口。",
        unsupported_window_kind: "窗口类型不支持。",
        panel_window_closed: "面板窗口已关闭。",
        preview_window_closed: "预览窗口已关闭。",
        preview_layer_not_ready: "预览绘制层尚未就绪。",
        main_thread_required: "需要主线程。",
        no_display: "找不到显示器。",
        invalid_link: "链接无效。",
        cannot_open: "无法打开这项内容。",
        no_paste_permission: "需要辅助功能权限才能自动粘贴；也可使用复制按钮。",
        no_paste_target: "没有可粘贴的目标应用，请从其他应用唤起面板。",
        paste_target_quit: "原应用已退出，请重新唤起面板。",
        focus_moved: "焦点已切换，请回到目标应用重新唤起面板。",
        cannot_return_to_target: "无法切回目标应用，请重新唤起面板。",
        paste_target_missing: "没有可粘贴的目标应用。",
        cannot_create_typing_event: "无法创建输入事件。",
        cannot_create_paste_event: "无法创建粘贴事件。",
    },
    service: Service {
        locked: "剪贴板已锁定，请解锁后继续。",
        search_failed: "搜索失败，请重试。",
        disconnected: "同步服务未响应。",
        interrupted: "后台请求已中断，请重试。",
        search_timeout: "搜索超时，请重试。",
        not_running: "无法连接 UniClipboard，请先启动并解锁桌面应用。",
        cannot_connect: "无法创建后台连接。",
        restore_failed: "无法复制这条记录，请刷新后重试。",
        restore_timeout: "复制超时，请重试。",
        action_failed: "操作失败，请重试。",
        tags_unavailable: "无法读取标签。",
        devices_unavailable: "无法读取设备。",
        preview_timeout: "预览加载超时。",
        preview_unreadable: "无法读取预览。",
        entry_gone: "内容已不可用。",
        image_unreadable: "无法读取图片。",
        image_gone: "图片已不可用。",
        image_bad_format: "图片格式错误。",
        image_unsupported: "图片格式不支持。",
        image_undecodable: "图片无法解码。",
        copy_failed: "复制失败，请重试。",
        no_paths: "没有可粘贴的文件路径。",
        preview_unreadable_retry: "无法读取预览，请重试。",
    },
};
