use super::{Count, Dates, Platform, Service, Text};

pub(super) static TEXT: Text = Text {
    search_placeholder: "搜尋，或輸入 # 標籤  @ 裝置  / 類型",
    actions: "操作",
    send_to: "發送到",
    actions_hint: "↑↓ 選擇 · ⏎ 執行 · esc 返回",
    nothing_to_open: "這筆記錄沒有可開啟的連結或檔案。",
    no_log_dir: "找不到日誌目錄。",
    first_use_title: "還沒有剪貼簿歷史",
    first_use_hint: "在任何裝置上複製內容，都會出現在這裡。",
    summon_anytime: "隨時喚出",
    locked_title: "應用程式介面已鎖定",
    unlock: "解鎖",
    disconnected_title: "同步服務未回應",
    reconnect_hint: "本次喚出期間恢復連線後會自動重新整理列表。",
    reconnect_now: "立即重新連線",
    view_logs: "查看日誌",
    close: "關閉",
    try_relaxing: "試試放寬：",
    apply_suggestion: "套用建議",
    clear: "清除",
    needs_app: "此功能需要在 UniClipboard 應用程式內使用。",
    host_gone: "無法聯繫主程式。",
    locked_hint_gui: "在主視窗輸入密碼解鎖，解鎖後這裡會自動重新整理。",
    open_main_window: "開啟主視窗",
    settings: "設定…",
    suggestions: "建議",
    accept_in_order: "依序接受",
    press_again: "再按",
    all_types: "全部",
    try_other_terms: "試試別的關鍵詞或篩選條件",
    searching: "搜尋中…",
    just_now: "剛剛",
    loading: "載入中…",
    loading_image: "正在載入圖片…",
    retry: "重試",
    fit_to_window: "完整顯示",
    actual_size: "原始尺寸",
    delete_hint_mac: "⌘⇧⌫ 刪除",
    delete_hint_other: "Ctrl+Shift+⌫ 刪除",
    shortcut_taken: "無法註冊快捷鍵，可能已被其他程式佔用。",
    preview_window_failed: "無法開啟預覽視窗。",
    copy: "複製",
    hidden_count: "還有 {n} 條",
    reconnecting: "正在自動重新連線（第 {n} 次）。",
    no_match: "沒有符合條件的內容",
    no_match_query: "沒有符合「{query}」的內容",
    paste: "貼上",
    paste_to: "貼上到 {name}",
    result_count: Count::same("{n} 條"),
    text_match_count: Count::same("{n} 條文字相符"),
    text_matches: "文字相符",
    dimension_type: "類型",
    dimension_tag: "標籤",
    dimension_source: "裝置",
    dimension_time: "時間",
    kind_text: "文字",
    kind_rich_text: "格式化文字",
    kind_image: "圖片",
    kind_file: "檔案",
    kind_link: "連結",
    kind_code: "程式碼",
    kind_directory: "資料夾",
    tag_favorited: "我的最愛",
    paste_plain: "貼上為純文字",
    paste_keep_open: "貼上並保持面板",
    copy_only: "只複製",
    paste_paths: "貼上檔案路徑",
    open: "開啟",
    reveal_file: "在資料夾中顯示",
    send_to_device: "發送到裝置",
    favorite: "加入我的最愛",
    unfavorite: "取消我的最愛",
    delete: "刪除",
    all_devices: "所有裝置",
    lines: Count::same("{n} 行"),
    characters: Count::same("{n} 個字元"),
    items: Count::same("{n} 項"),
    from_device: "來自 {name}",
    remove_type: "移除 /{value}",
    remove_all_types: "移除所有類型",
    remove_tag: "移除 #{value}",
    remove_all_tags: "移除所有標籤",
    widen_time: "時間範圍擴大到全部",
    remove_device: "移除 @{name}，包含所有裝置",
    include_all_devices: "包含所有裝置",
    dates: Dates {
        today: "今天",
        yesterday: "昨天",
        day_before_yesterday: "前天",
        this_week: "本週",
        last_week: "上週",
        this_month: "本月",
        last_month: "上月",
        last_days: Count::same("最近{n}天"),
        months: [
            "1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月",
        ],
        day: "{m}月{d}日",
        day_with_year: "{y}年{m}月{d}日",
        end_day_same_month: "{d}日",
        month: "{m}月",
        month_with_year: "{y}年{m}月",
        since: "{date}起",
        until: "{date}前",
    },
    platform: Platform {
        unsupported: "此平台暫不支援該功能。",
        panel_window_inaccessible: "無法存取面板視窗。",
        preview_window_inaccessible: "無法存取預覽視窗。",
        unsupported_window_kind: "不支援的視窗類型。",
        panel_window_closed: "面板視窗已關閉。",
        preview_window_closed: "預覽視窗已關閉。",
        preview_layer_not_ready: "預覽繪製層尚未就緒。",
        main_thread_required: "需要主執行緒。",
        no_display: "找不到顯示器。",
        invalid_link: "連結無效。",
        cannot_open: "無法開啟此項內容。",
        no_paste_permission: "需要輔助使用權限才能自動貼上；也可使用複製按鈕。",
        no_paste_target: "沒有可貼上的目標應用程式，請從其他應用程式喚出面板。",
        paste_target_quit: "原應用程式已結束，請重新喚出面板。",
        focus_moved: "焦點已切換，請回到目標應用程式重新喚出面板。",
        cannot_return_to_target: "無法切回目標應用程式，請重新喚出面板。",
        paste_target_missing: "沒有可貼上的目標應用程式。",
        cannot_create_typing_event: "無法建立輸入事件。",
        cannot_create_paste_event: "無法建立貼上事件。",
    },
    service: Service {
        locked: "剪貼簿已鎖定，請解鎖後繼續。",
        search_failed: "搜尋失敗，請重試。",
        disconnected: "同步服務未回應。",
        interrupted: "背景請求已中斷，請重試。",
        search_timeout: "搜尋逾時，請重試。",
        not_running: "無法連接 UniClipboard，請先啟動並解鎖桌面應用程式。",
        cannot_connect: "無法建立背景連線。",
        restore_failed: "無法複製這筆記錄，請重新整理後重試。",
        restore_timeout: "複製逾時，請重試。",
        action_failed: "操作失敗，請重試。",
        tags_unavailable: "無法讀取標籤。",
        devices_unavailable: "無法讀取裝置。",
        preview_timeout: "預覽載入逾時。",
        preview_unreadable: "無法讀取預覽。",
        entry_gone: "內容已無法使用。",
        image_unreadable: "無法讀取圖片。",
        image_gone: "圖片已無法使用。",
        image_bad_format: "圖片格式錯誤。",
        image_unsupported: "不支援的圖片格式。",
        image_undecodable: "圖片無法解碼。",
        copy_failed: "複製失敗，請重試。",
        no_paths: "沒有可貼上的檔案路徑。",
        preview_unreadable_retry: "無法讀取預覽，請重試。",
    },
};
