; NSIS installer of the Go GUI (Wails) for UniClipboard.
;
; Why this is not Wails' project.nsi.tmpl (v3.0.0-beta.28): that template needs wails_tools.nsh generated by the
; wails3 CLI, uses another uninstall key and install directory than the Tauri installer, understands no /UPDATE or
; /ARGS, stops no running process and compares no versions, so it could not upgrade an existing Tauri installation in
; place nor be the target of the Tauri updater's `/P /R /UPDATE /ARGS ...` invocation. This script is a deliberately
; small implementation of the same contract (see the Tauri installer template embedded in the Tauri CLI and
; tauri-plugin-updater's install_inner):
;
;   /P        passive: progress only, no wizard pages
;   /S        silent (NSIS built-in)
;   /UPDATE   an update of an existing installation: keep shortcuts, do not reinstall WebView2
;   /R        start the new version when done (passive or silent only)
;   /ARGS ... the arguments the running application had; passed to the restarted application
;   /D=<dir>  install directory (NSIS built-in)
;
; Same registry identity as the Tauri installer (per-user): Software\Microsoft\Windows\CurrentVersion\Uninstall\<product>
; with InstallLocation / UninstallString, so Add/Remove Programs, the uninstaller and the next update keep working.
;
; Not implemented relative to the Tauri template (recorded gaps): version comparison / downgrade protection, the
; "delete app data" uninstall option, WiX migration, language selector, per-machine install mode.
;
; Required defines (package_windows.py): PRODUCTNAME VERSION VERSIONWITHBUILD MANUFACTURER BUNDLEID MAINBINARYNAME
; SRC_MAIN SRC_DAEMON ICON OUTFILE HOOKS

Unicode true
ManifestDPIAware true
SetCompressor /SOLID lzma
RequestExecutionLevel user

!include MUI2.nsh
!include FileFunc.nsh
!include LogicLib.nsh
!include x64.nsh
!include "${HOOKS}"

!define UNINSTKEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCTNAME}"
!define MANUPRODUCTKEY "Software\${MANUFACTURER}\${PRODUCTNAME}"
!define RUNKEY "Software\Microsoft\Windows\CurrentVersion\Run"
!define WEBVIEW2APPGUID "{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}"
!define PLACEHOLDER_INSTALL_DIR "placeholder\${PRODUCTNAME}"

Var PassiveMode
Var UpdateMode

Name "${PRODUCTNAME}"
OutFile "${OUTFILE}"
InstallDir "${PLACEHOLDER_INSTALL_DIR}"
VIProductVersion "${VERSIONWITHBUILD}"
VIAddVersionKey "ProductName" "${PRODUCTNAME}"
VIAddVersionKey "FileDescription" "${PRODUCTNAME}"
VIAddVersionKey "FileVersion" "${VERSION}"
VIAddVersionKey "ProductVersion" "${VERSION}"
VIAddVersionKey "LegalCopyright" "${MANUFACTURER}"

!define MUI_ICON "${ICON}"
!define MUI_UNICON "${ICON}"
!define MUI_PAGE_CUSTOMFUNCTION_PRE SkipIfPassive
!insertmacro MUI_PAGE_WELCOME
!define MUI_PAGE_CUSTOMFUNCTION_PRE SkipIfPassive
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!define MUI_FINISHPAGE_NOAUTOCLOSE
!define MUI_FINISHPAGE_RUN
!define MUI_FINISHPAGE_RUN_FUNCTION RunMainBinary
!define MUI_PAGE_CUSTOMFUNCTION_PRE SkipIfPassive
!insertmacro MUI_PAGE_FINISH
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_LANGUAGE "English"

Function SkipIfPassive
  ${IfThen} $PassiveMode = 1 ${|} Abort ${|}
FunctionEnd

Function RunMainBinary
  Exec '"$INSTDIR\${MAINBINARYNAME}"'
FunctionEnd

; The previous install location: the uninstall key written by the Tauri or this installer, then the manufacturer key.
Function RestorePreviousInstallLocation
  ReadRegStr $4 HKCU "${UNINSTKEY}" "InstallLocation"
  ${If} $4 != ""
    ; Tauri stores the path in double quotes.
    StrCpy $5 $4 1
    ${If} $5 == '"'
      StrLen $6 $4
      IntOp $6 $6 - 2
      StrCpy $4 $4 $6 1
    ${EndIf}
  ${Else}
    ReadRegStr $4 HKCU "${MANUPRODUCTKEY}" ""
  ${EndIf}
  ${If} $4 != ""
    StrCpy $INSTDIR $4
  ${EndIf}
FunctionEnd

Function .onInit
  ${GetOptions} $CMDLINE "/P" $PassiveMode
  ${IfNot} ${Errors}
    StrCpy $PassiveMode 1
  ${EndIf}
  ${GetOptions} $CMDLINE "/UPDATE" $UpdateMode
  ${IfNot} ${Errors}
    StrCpy $UpdateMode 1
  ${EndIf}
  ${If} $INSTDIR == "${PLACEHOLDER_INSTALL_DIR}"
    StrCpy $INSTDIR "$LOCALAPPDATA\${PRODUCTNAME}"
    Call RestorePreviousInstallLocation
  ${EndIf}
FunctionEnd

Section "WebView2"
  ; The Wails window needs the WebView2 runtime. Skip when present, and on an update (it was there before).
  ${If} ${RunningX64}
    ReadRegStr $4 HKLM "SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\${WEBVIEW2APPGUID}" "pv"
  ${Else}
    ReadRegStr $4 HKLM "SOFTWARE\Microsoft\EdgeUpdate\Clients\${WEBVIEW2APPGUID}" "pv"
  ${EndIf}
  ${If} $4 == ""
    ReadRegStr $4 HKCU "SOFTWARE\Microsoft\EdgeUpdate\Clients\${WEBVIEW2APPGUID}" "pv"
  ${EndIf}
  ${If} $4 == ""
  ${AndIf} $UpdateMode <> 1
    Delete "$TEMP\MicrosoftEdgeWebview2Setup.exe"
    DetailPrint "Downloading the WebView2 bootstrapper..."
    NSISdl::download "https://go.microsoft.com/fwlink/p/?LinkId=2124703" "$TEMP\MicrosoftEdgeWebview2Setup.exe"
    Pop $0
    ${If} $0 != "success"
      Abort "Could not download the WebView2 runtime ($0). Install it from https://developer.microsoft.com/microsoft-edge/webview2/ and run this installer again."
    ${EndIf}
    ExecWait '"$TEMP\MicrosoftEdgeWebview2Setup.exe" /silent /install' $1
    ${If} $1 <> 0
      Abort "The WebView2 runtime installation failed ($1)."
    ${EndIf}
  ${EndIf}
SectionEnd

Section "Install"
  SetOutPath $INSTDIR
  ; Stops the running GUI first, then the daemon, and waits until its image is writable (shared with the Tauri
  ; installer, which has the same file lock problem).
  !insertmacro NSIS_HOOK_PREINSTALL
  File "/oname=${MAINBINARYNAME}" "${SRC_MAIN}"
  File "/oname=uniclipd.exe" "${SRC_DAEMON}"
  WriteUninstaller "$INSTDIR\uninstall.exe"

  WriteRegStr HKCU "${MANUPRODUCTKEY}" "" $INSTDIR
  WriteRegStr HKCU "${UNINSTKEY}" "MainBinaryName" "${MAINBINARYNAME}"
  WriteRegStr HKCU "${UNINSTKEY}" "DisplayName" "${PRODUCTNAME}"
  WriteRegStr HKCU "${UNINSTKEY}" "DisplayIcon" '"$INSTDIR\${MAINBINARYNAME}"'
  WriteRegStr HKCU "${UNINSTKEY}" "DisplayVersion" "${VERSION}"
  WriteRegStr HKCU "${UNINSTKEY}" "Publisher" "${MANUFACTURER}"
  WriteRegStr HKCU "${UNINSTKEY}" "InstallLocation" '"$INSTDIR"'
  WriteRegStr HKCU "${UNINSTKEY}" "UninstallString" '"$INSTDIR\uninstall.exe"'
  WriteRegDWORD HKCU "${UNINSTKEY}" "NoModify" 1
  WriteRegDWORD HKCU "${UNINSTKEY}" "NoRepair" 1

  CreateShortcut "$SMPROGRAMS\${PRODUCTNAME}.lnk" "$INSTDIR\${MAINBINARYNAME}"
  ; Passive and silent runs skip the finish page, so the desktop shortcut is created here.
  ${If} $PassiveMode = 1
  ${OrIf} ${Silent}
    CreateShortcut "$DESKTOP\${PRODUCTNAME}.lnk" "$INSTDIR\${MAINBINARYNAME}"
  ${EndIf}
  ${If} $PassiveMode = 1
    SetAutoClose true
  ${EndIf}
SectionEnd

; /R restarts the application with the arguments after /ARGS (an update from the running application).
Function .onInstSuccess
  ${If} $PassiveMode = 1
  ${OrIf} ${Silent}
    ${GetOptions} $CMDLINE "/R" $R0
    ${IfNot} ${Errors}
      ${GetOptions} $CMDLINE "/ARGS" $R0
      Exec '"$INSTDIR\${MAINBINARYNAME}" $R0'
    ${EndIf}
  ${EndIf}
FunctionEnd

Function un.onInit
  ${GetOptions} $CMDLINE "/P" $PassiveMode
  ${IfNot} ${Errors}
    StrCpy $PassiveMode 1
  ${EndIf}
  ${GetOptions} $CMDLINE "/UPDATE" $UpdateMode
  ${IfNot} ${Errors}
    StrCpy $UpdateMode 1
  ${EndIf}
FunctionEnd

Section "Uninstall"
  !insertmacro NSIS_HOOK_PREUNINSTALL
  Delete "$INSTDIR\${MAINBINARYNAME}"
  Delete "$INSTDIR\uniclipd.exe"
  Delete "$INSTDIR\uninstall.exe"
  RMDir "$INSTDIR"
  ${If} $UpdateMode <> 1
    Delete "$SMPROGRAMS\${PRODUCTNAME}.lnk"
    Delete "$DESKTOP\${PRODUCTNAME}.lnk"
    ; Do not leave a login item behind for a program that is gone (kept on updates).
    DeleteRegValue HKCU "${RUNKEY}" "${PRODUCTNAME}"
  ${EndIf}
  DeleteRegKey HKCU "${UNINSTKEY}"
  DeleteRegKey /ifempty HKCU "${MANUPRODUCTKEY}"
  ${If} $PassiveMode = 1
  ${OrIf} $UpdateMode = 1
    SetAutoClose true
  ${EndIf}
SectionEnd
