; NSIS installer of the Go GUI (Wails) for UniClipboard.
;
; Why this is not Wails' project.nsi.tmpl (v3.0.0-beta.28): that template needs wails_tools.nsh generated by the
; wails3 CLI, uses another uninstall key and install directory than the Tauri installer, understands no /UPDATE or
; /ARGS, stops no running process and compares no versions, so it could not upgrade an existing Tauri installation in
; place nor be the target of the Tauri updater's `/P /R /UPDATE /ARGS ...` invocation. This script is a deliberately
; small implementation of the same contract (see the Tauri installer template embedded in the Tauri CLI and
; tauri-plugin-updater's install_inner):
;
;   /P        passive: progress only, no wizard pages
;   /S        silent (NSIS built-in)
;   /UPDATE   an update of an existing installation: keep shortcuts, do not reinstall WebView2
;   /R        start the new version when done (passive or silent only)
;   /ARGS ... the arguments the running application had; passed to the restarted application
;   /D=<dir>  install directory (NSIS built-in)
;   /DELETEAPPDATA  uninstaller only: delete the application data, like the check box (scripted and silent uninstalls)
;
; Same registry identity as the Tauri installer (per-user): Software\Microsoft\Windows\CurrentVersion\Uninstall\<product>
; with InstallLocation / UninstallString, so Add/Remove Programs, the uninstaller and the next update keep working.
;
; Parity with the Tauri template: version comparison with `nsis_tauri_utils::SemverCompare` (the same plugin, fetched and
; hash-checked by package_windows.py) and refusal of a downgrade; the "delete app data" uninstall option.
; Deliberately not implemented, with the reason: WiX migration (the retired Tauri configuration bundled `nsis` only, no MSI was ever
; shipped), the language selector (`displayLanguageSelector` is not set, English only), per-machine install mode
; (`installMode` is not set: current user). The Tauri template's interactive "reinstall / uninstall first" page is
; replaced by overwriting in place (same registry identity, same files).
;
; Required defines (package_windows.py): PRODUCTNAME VERSION VERSIONWITHBUILD MANUFACTURER BUNDLEID MAINBINARYNAME
; SRC_MAIN SRC_DAEMON SRC_HELPER ICON OUTFILE HOOKS PLUGINDIR, and SRC_UNINSTALLER (the installer proper only)
;
; The script is compiled twice (package_windows.py), the "signing an uninstaller externally" pattern of NSIS:
;   -DBUILD_UNINSTALLER   a generator whose only job is to write uninstall.exe next to itself (it holds the uninstall pages
;                         and sections). The uninstaller can then be signed like any other file;
;   (without the define)  the installer proper, which carries that finished (signed) uninstall.exe as a plain file and
;                         has no uninstall code of its own.

Unicode true
ManifestDPIAware true
SetCompressor /SOLID lzma
RequestExecutionLevel user

!include MUI2.nsh
!include FileFunc.nsh
!include LogicLib.nsh
!include x64.nsh
!addplugindir /x86-unicode "${PLUGINDIR}"
!include "${HOOKS}"

!define UNINSTKEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCTNAME}"
!define MANUPRODUCTKEY "Software\${MANUFACTURER}\${PRODUCTNAME}"
!define RUNKEY "Software\Microsoft\Windows\CurrentVersion\Run"
!define WEBVIEW2APPGUID "{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}"
!define PLACEHOLDER_INSTALL_DIR "placeholder\${PRODUCTNAME}"

Var PassiveMode
Var UpdateMode

Name "${PRODUCTNAME}"
OutFile "${OUTFILE}"
InstallDir "${PLACEHOLDER_INSTALL_DIR}"
VIProductVersion "${VERSIONWITHBUILD}"
VIAddVersionKey "ProductName" "${PRODUCTNAME}"
VIAddVersionKey "FileDescription" "${PRODUCTNAME}"
VIAddVersionKey "FileVersion" "${VERSION}"
VIAddVersionKey "ProductVersion" "${VERSION}"
VIAddVersionKey "LegalCopyright" "${MANUFACTURER}"

!define MUI_ICON "${ICON}"
!define MUI_UNICON "${ICON}"
!define MUI_PAGE_CUSTOMFUNCTION_PRE SkipIfPassive
!insertmacro MUI_PAGE_WELCOME
!define MUI_PAGE_CUSTOMFUNCTION_PRE SkipIfPassive
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!define MUI_FINISHPAGE_NOAUTOCLOSE
!define MUI_FINISHPAGE_RUN
!define MUI_FINISHPAGE_RUN_FUNCTION RunMainBinary
!define MUI_PAGE_CUSTOMFUNCTION_PRE SkipIfPassive
!insertmacro MUI_PAGE_FINISH
!ifdef BUILD_UNINSTALLER
; "Delete app data" check box on the uninstall confirmation page (Tauri template, adapted).
Var DeleteAppDataCheckbox
Var DeleteAppDataCheckboxState
!define MUI_PAGE_CUSTOMFUNCTION_SHOW un.ConfirmShow
!define MUI_PAGE_CUSTOMFUNCTION_LEAVE un.ConfirmLeave
!define MUI_PAGE_CUSTOMFUNCTION_PRE un.SkipIfPassive
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!endif
!insertmacro MUI_LANGUAGE "English"

Function SkipIfPassive
  ${IfThen} $PassiveMode = 1 ${|} Abort ${|}
FunctionEnd

Function RunMainBinary
  Exec '"$INSTDIR\${MAINBINARYNAME}"'
FunctionEnd

; The previous install location: the uninstall key written by the Tauri or this installer, then the manufacturer key.
Function RestorePreviousInstallLocation
  ReadRegStr $4 HKCU "${UNINSTKEY}" "InstallLocation"
  ${If} $4 != ""
    ; Tauri stores the path in double quotes.
    StrCpy $5 $4 1
    ${If} $5 == '"'
      StrLen $6 $4
      IntOp $6 $6 - 2
      StrCpy $4 $4 $6 1
    ${EndIf}
  ${Else}
    ReadRegStr $4 HKCU "${MANUPRODUCTKEY}" ""
  ${EndIf}
  ${If} $4 != ""
    StrCpy $INSTDIR $4
  ${EndIf}
FunctionEnd

Function .onInit
!ifdef BUILD_UNINSTALLER
  ; Generator: write the uninstaller and stop, nothing is installed.
  WriteUninstaller "$EXEDIR\uninstall.exe"
  Quit
!endif
  ${GetOptions} $CMDLINE "/P" $PassiveMode
  ${IfNot} ${Errors}
    StrCpy $PassiveMode 1
  ${EndIf}
  ${GetOptions} $CMDLINE "/UPDATE" $UpdateMode
  ${IfNot} ${Errors}
    StrCpy $UpdateMode 1
  ${EndIf}
  ${If} $INSTDIR == "${PLACEHOLDER_INSTALL_DIR}"
    StrCpy $INSTDIR "$LOCALAPPDATA\${PRODUCTNAME}"
    Call RestorePreviousInstallLocation
  ${EndIf}
  ; Refuse to replace a newer installed version (Tauri: ALLOWDOWNGRADES false). SemverCompare gives 1 for an
  ; upgrade, 0 for the same version and -1 for a downgrade; an unreadable installed version is treated as older.
  ReadRegStr $R1 HKCU "${UNINSTKEY}" "DisplayVersion"
  ${If} $R1 != ""
    nsis_tauri_utils::SemverCompare "${VERSION}" $R1
    Pop $R0
    ${If} $R0 = -1
      ${If} ${Silent}
      ${OrIf} $PassiveMode = 1
        System::Call 'kernel32::AttachConsole(i -1)i.r0'
        ${If} $0 <> 0
          System::Call 'kernel32::GetStdHandle(i -11)i.r0'
          FileWrite $0 "A newer version of ${PRODUCTNAME} ($R1) is already installed; downgrades are not allowed.$\r$\n"
        ${EndIf}
      ${Else}
        MessageBox MB_ICONSTOP "A newer version of ${PRODUCTNAME} ($R1) is already installed. Uninstall it first to install version ${VERSION}."
      ${EndIf}
      Abort
    ${EndIf}
  ${EndIf}
FunctionEnd

Section "WebView2"
  ; The Wails window needs the WebView2 runtime. Skip when present, and on an update (it was there before).
  ${If} ${RunningX64}
    ReadRegStr $4 HKLM "SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\${WEBVIEW2APPGUID}" "pv"
  ${Else}
    ReadRegStr $4 HKLM "SOFTWARE\Microsoft\EdgeUpdate\Clients\${WEBVIEW2APPGUID}" "pv"
  ${EndIf}
  ${If} $4 == ""
    ReadRegStr $4 HKCU "SOFTWARE\Microsoft\EdgeUpdate\Clients\${WEBVIEW2APPGUID}" "pv"
  ${EndIf}
  ${If} $4 == ""
  ${AndIf} $UpdateMode <> 1
    Delete "$TEMP\MicrosoftEdgeWebview2Setup.exe"
    DetailPrint "Downloading the WebView2 bootstrapper..."
    NSISdl::download "https://go.microsoft.com/fwlink/p/?LinkId=2124703" "$TEMP\MicrosoftEdgeWebview2Setup.exe"
    Pop $0
    ${If} $0 != "success"
      Abort "Could not download the WebView2 runtime ($0). Install it from https://developer.microsoft.com/microsoft-edge/webview2/ and run this installer again."
    ${EndIf}
    ExecWait '"$TEMP\MicrosoftEdgeWebview2Setup.exe" /silent /install' $1
    ${If} $1 <> 0
      Abort "The WebView2 runtime installation failed ($1)."
    ${EndIf}
  ${EndIf}
SectionEnd

Section "Install"
  SetOutPath $INSTDIR
  ; Stops the running GUI first, then the daemon, and waits until its image is writable (shared with the Tauri
  ; installer, which has the same file lock problem).
  !insertmacro NSIS_HOOK_PREINSTALL
  File "/oname=${MAINBINARYNAME}" "${SRC_MAIN}"
  File "/oname=uniclipd.exe" "${SRC_DAEMON}"
  ; The native quick panel: the app starts it as a sibling process.
  File "/oname=uniclip-quick-panel.exe" "${SRC_HELPER}"
!ifdef BUILD_UNINSTALLER
  WriteUninstaller "$INSTDIR\uninstall.exe"
!else
  File "/oname=uninstall.exe" "${SRC_UNINSTALLER}"
!endif

  WriteRegStr HKCU "${MANUPRODUCTKEY}" "" $INSTDIR
  WriteRegStr HKCU "${UNINSTKEY}" "MainBinaryName" "${MAINBINARYNAME}"
  WriteRegStr HKCU "${UNINSTKEY}" "DisplayName" "${PRODUCTNAME}"
  WriteRegStr HKCU "${UNINSTKEY}" "DisplayIcon" '"$INSTDIR\${MAINBINARYNAME}"'
  WriteRegStr HKCU "${UNINSTKEY}" "DisplayVersion" "${VERSION}"
  WriteRegStr HKCU "${UNINSTKEY}" "Publisher" "${MANUFACTURER}"
  WriteRegStr HKCU "${UNINSTKEY}" "InstallLocation" '"$INSTDIR"'
  WriteRegStr HKCU "${UNINSTKEY}" "UninstallString" '"$INSTDIR\uninstall.exe"'
  WriteRegDWORD HKCU "${UNINSTKEY}" "NoModify" 1
  WriteRegDWORD HKCU "${UNINSTKEY}" "NoRepair" 1

  CreateShortcut "$SMPROGRAMS\${PRODUCTNAME}.lnk" "$INSTDIR\${MAINBINARYNAME}"
  ; Passive and silent runs skip the finish page, so the desktop shortcut is created here.
  ${If} $PassiveMode = 1
  ${OrIf} ${Silent}
    CreateShortcut "$DESKTOP\${PRODUCTNAME}.lnk" "$INSTDIR\${MAINBINARYNAME}"
  ${EndIf}
  ${If} $PassiveMode = 1
    SetAutoClose true
  ${EndIf}
SectionEnd

; /R restarts the application with the arguments after /ARGS (an update from the running application).
Function .onInstSuccess
  ${If} $PassiveMode = 1
  ${OrIf} ${Silent}
    ${GetOptions} $CMDLINE "/R" $R0
    ${IfNot} ${Errors}
      ${GetOptions} $CMDLINE "/ARGS" $R0
      Exec '"$INSTDIR\${MAINBINARYNAME}" $R0'
    ${EndIf}
  ${EndIf}
FunctionEnd

!ifdef BUILD_UNINSTALLER
Function un.SkipIfPassive
  ${IfThen} $PassiveMode = 1 ${|} Abort ${|}
FunctionEnd

Function un.ConfirmShow
  FindWindow $1 "#32770" "" $HWNDPARENT
  System::Call "user32::GetDpiForWindow(p r1) i .r2"
  ${If} $2 = 0
    StrCpy $2 96
  ${EndIf}
  IntOp $5 100 * $2
  IntOp $6 400 * $2
  IntOp $7 25 * $2
  IntOp $5 $5 / 96
  IntOp $6 $6 / 96
  IntOp $7 $7 / 96
  System::Call 'user32::CreateWindowEx(i ${__NSD_CheckBox_EXSTYLE}, w "${__NSD_CheckBox_CLASS}", w "Delete the application data", i ${__NSD_CheckBox_STYLE}, i 0, i r5, i r6, i r7, p r1, i0, i0, i0) i .s'
  Pop $DeleteAppDataCheckbox
  SendMessage $HWNDPARENT ${WM_GETFONT} 0 0 $1
  SendMessage $DeleteAppDataCheckbox ${WM_SETFONT} $1 1
FunctionEnd

Function un.ConfirmLeave
  SendMessage $DeleteAppDataCheckbox ${BM_GETCHECK} 0 0 $DeleteAppDataCheckboxState
FunctionEnd

Function un.onInit
  ${GetOptions} $CMDLINE "/P" $PassiveMode
  ${IfNot} ${Errors}
    StrCpy $PassiveMode 1
  ${EndIf}
  ; /DELETEAPPDATA is the scripted form of the check box (a silent uninstall shows no page): same effect, never on /UPDATE.
  ${GetOptions} $CMDLINE "/DELETEAPPDATA" $R0
  ${IfNot} ${Errors}
    StrCpy $DeleteAppDataCheckboxState 1
  ${EndIf}
  ${GetOptions} $CMDLINE "/UPDATE" $UpdateMode
  ${IfNot} ${Errors}
    StrCpy $UpdateMode 1
  ${EndIf}
FunctionEnd

Section "Uninstall"
  !insertmacro NSIS_HOOK_PREUNINSTALL
  Delete "$INSTDIR\${MAINBINARYNAME}"
  Delete "$INSTDIR\uniclipd.exe"
  Delete "$INSTDIR\uniclip-quick-panel.exe"
  Delete "$INSTDIR\uninstall.exe"
  RMDir "$INSTDIR"
  ${If} $UpdateMode <> 1
    Delete "$SMPROGRAMS\${PRODUCTNAME}.lnk"
    Delete "$DESKTOP\${PRODUCTNAME}.lnk"
    ; Do not leave a login item behind for a program that is gone (kept on updates).
    DeleteRegValue HKCU "${RUNKEY}" "${PRODUCTNAME}"
  ${EndIf}
  DeleteRegKey HKCU "${UNINSTKEY}"
  DeleteRegKey /ifempty HKCU "${MANUPRODUCTKEY}"
  ; The data the application keeps for itself (database, keys, caches: %LOCALAPPDATA%\<identifier>, and the WebView2
  ; profile under %APPDATA%) is only removed when asked for, never on an update (Tauri template behavior).
  ${If} $DeleteAppDataCheckboxState = 1
  ${AndIf} $UpdateMode <> 1
    DeleteRegKey /ifempty HKCU "Software\${MANUFACTURER}"
    SetShellVarContext current
    RmDir /r "$APPDATA\${BUNDLEID}"
    RmDir /r "$LOCALAPPDATA\${BUNDLEID}"
  ${EndIf}
  ${If} $PassiveMode = 1
  ${OrIf} $UpdateMode = 1
    SetAutoClose true
  ${EndIf}
SectionEnd
!endif
