; NSIS installer of the Go GUI (Wails) for UniClipboard.
;
; Why this is not Wails' project.nsi.tmpl (v3.0.0-beta.28): that template needs wails_tools.nsh generated by the
; wails3 CLI, uses another uninstall key and install directory than the Tauri installer, understands no /UPDATE or
; /ARGS, stops no running process and compares no versions, so it could not upgrade an existing Tauri installation in
; place nor be the target of the Tauri updater's `/P /R /UPDATE /ARGS ...` invocation. This script is a deliberately
; small implementation of the same contract (see the Tauri installer template embedded in the Tauri CLI and
; tauri-plugin-updater's install_inner):
;
;   /P        passive: progress only, no wizard pages
;   /S        silent (NSIS built-in)
;   /UPDATE   an update of an existing installation: keep shortcuts, do not reinstall WebView2
;   /R        start the new version when done (passive or silent only)
;   /ARGS ... the arguments the running application had; passed to the restarted application
;   /D=<dir>  install directory (NSIS built-in)
;
; Same registry identity as the Tauri installer (per-user): Software\Microsoft\Windows\CurrentVersion\Uninstall\<product>
; with InstallLocation / UninstallString, so Add/Remove Programs, the uninstaller and the next update keep working.
;
; Parity with the Tauri template: version comparison with `nsis_tauri_utils::SemverCompare` (the same plugin, fetched and
; hash-checked by package_windows.py) and refusal of a downgrade; the "delete app data" uninstall option.
; The interactive "already installed" page (PageReinstall / PageLeaveReinstall and its English strings) is the Tauri
; template's own text, ported without the WiX branch; e2e/installer_template_diff.py extracts the template from the
; pinned Tauri CLI and checks that nothing else differs.
; Deliberately not implemented, with the reason: WiX migration (tauri.conf.json bundles `nsis` only, no MSI was ever
; shipped), the language selector (`displayLanguageSelector` is not set, English only), per-machine install mode
; (`installMode` is not set: current user).
;
; Required defines (package_windows.py): PRODUCTNAME VERSION VERSIONWITHBUILD MANUFACTURER BUNDLEID MAINBINARYNAME
; SRC_MAIN SRC_DAEMON ICON OUTFILE HOOKS PLUGINDIR

Unicode true
ManifestDPIAware true
SetCompressor /SOLID lzma
RequestExecutionLevel user

!include MUI2.nsh
!include FileFunc.nsh
!include LogicLib.nsh
!include x64.nsh
!addplugindir /x86-unicode "${PLUGINDIR}"
!include "${HOOKS}"

!define UNINSTKEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCTNAME}"
!define MANUPRODUCTKEY "Software\${MANUFACTURER}\${PRODUCTNAME}"
!define RUNKEY "Software\Microsoft\Windows\CurrentVersion\Run"
!define WEBVIEW2APPGUID "{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}"
!define PLACEHOLDER_INSTALL_DIR "placeholder\${PRODUCTNAME}"

Var PassiveMode
Var UpdateMode

Name "${PRODUCTNAME}"
OutFile "${OUTFILE}"
InstallDir "${PLACEHOLDER_INSTALL_DIR}"
VIProductVersion "${VERSIONWITHBUILD}"
VIAddVersionKey "ProductName" "${PRODUCTNAME}"
VIAddVersionKey "FileDescription" "${PRODUCTNAME}"
VIAddVersionKey "FileVersion" "${VERSION}"
VIAddVersionKey "ProductVersion" "${VERSION}"
VIAddVersionKey "LegalCopyright" "${MANUFACTURER}"

!define MUI_ICON "${ICON}"
!define MUI_UNICON "${ICON}"
!define MUI_PAGE_CUSTOMFUNCTION_PRE SkipIfPassive
!insertmacro MUI_PAGE_WELCOME
; Custom page that asks whether to reinstall/uninstall, only if a previous installation was detected (Tauri template).
Var ReinstallPageCheck
Var SavedRunValue
Page custom PageReinstall PageLeaveReinstall
!define MUI_PAGE_CUSTOMFUNCTION_PRE SkipIfPassive
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!define MUI_FINISHPAGE_NOAUTOCLOSE
!define MUI_FINISHPAGE_RUN
!define MUI_FINISHPAGE_RUN_FUNCTION RunMainBinary
!define MUI_PAGE_CUSTOMFUNCTION_PRE SkipIfPassive
!insertmacro MUI_PAGE_FINISH
; "Delete app data" check box on the uninstall confirmation page (Tauri template, adapted).
Var DeleteAppDataCheckbox
Var DeleteAppDataCheckboxState
!define MUI_PAGE_CUSTOMFUNCTION_SHOW un.ConfirmShow
!define MUI_PAGE_CUSTOMFUNCTION_LEAVE un.ConfirmLeave
!define MUI_PAGE_CUSTOMFUNCTION_PRE un.SkipIfPassive
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_LANGUAGE "English"

; English strings of the Tauri template (tauri-cli 2.11.1), used by the page below.
LangString addOrReinstall ${LANG_ENGLISH} "Add/Reinstall components"
LangString alreadyInstalled ${LANG_ENGLISH} "Already Installed"
LangString alreadyInstalledLong ${LANG_ENGLISH} "${PRODUCTNAME} ${VERSION} is already installed. Select the operation you want to perform and click Next to continue."
LangString chooseMaintenanceOption ${LANG_ENGLISH} "Choose the maintenance option to perform."
LangString choowHowToInstall ${LANG_ENGLISH} "Choose how you want to install ${PRODUCTNAME}."
LangString dontUninstall ${LANG_ENGLISH} "Do not uninstall"
LangString dontUninstallDowngrade ${LANG_ENGLISH} "Do not uninstall (Downgrading without uninstall is disabled for this installer)"
LangString newerVersionInstalled ${LANG_ENGLISH} "A newer version of ${PRODUCTNAME} is already installed! It is not recommended that you install an older version. If you really want to install this older version, it's better to uninstall the current version first. Select the operation you want to perform and click Next to continue."
LangString older ${LANG_ENGLISH} "older"
LangString olderOrUnknownVersionInstalled ${LANG_ENGLISH} "An $R4 version of ${PRODUCTNAME} is installed on your system. It's recommended that you uninstall the current version before installing. Select the operation you want to perform and click Next to continue."
LangString unableToUninstall ${LANG_ENGLISH} "Unable to uninstall!"
LangString uninstallApp ${LANG_ENGLISH} "Uninstall ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_ENGLISH} "Uninstall before installing"
LangString unknown ${LANG_ENGLISH} "unknown"

Function PageReinstall
  ; Check if there is an existing installation, if not, abort the reinstall page
  ReadRegStr $R0 HKCU "${UNINSTKEY}" ""
  ReadRegStr $R1 HKCU "${UNINSTKEY}" "UninstallString"
  ${IfThen} "$R0$R1" == "" ${|} Abort ${|}

  ; Compare this installar version with the existing installation
  ; and modify the messages presented to the user accordingly
  StrCpy $R4 "$(older)"
  ReadRegStr $R0 HKCU "${UNINSTKEY}" "DisplayVersion"
  ${IfThen} $R0 == "" ${|} StrCpy $R4 "$(unknown)" ${|}

  nsis_tauri_utils::SemverCompare "${VERSION}" $R0
  Pop $R0
  ; Reinstalling the same version
  ${If} $R0 = 0
    StrCpy $R1 "$(alreadyInstalledLong)"
    StrCpy $R2 "$(addOrReinstall)"
    StrCpy $R3 "$(uninstallApp)"
    !insertmacro MUI_HEADER_TEXT "$(alreadyInstalled)" "$(chooseMaintenanceOption)"
  ; Upgrading
  ${ElseIf} $R0 = 1
    StrCpy $R1 "$(olderOrUnknownVersionInstalled)"
    StrCpy $R2 "$(uninstallBeforeInstalling)"
    StrCpy $R3 "$(dontUninstall)"
    !insertmacro MUI_HEADER_TEXT "$(alreadyInstalled)" "$(choowHowToInstall)"
  ; Downgrading (the Tauri configuration has no allowDowngrades, so downgrading without uninstalling is disabled)
  ${ElseIf} $R0 = -1
    StrCpy $R1 "$(newerVersionInstalled)"
    StrCpy $R2 "$(uninstallBeforeInstalling)"
    StrCpy $R3 "$(dontUninstallDowngrade)"
    !insertmacro MUI_HEADER_TEXT "$(alreadyInstalled)" "$(choowHowToInstall)"
  ${Else}
    Abort
  ${EndIf}

  ; Skip showing the page if passive
  ;
  ; Note that we don't call this earlier at the begining
  ; of this function because we need to populate some variables
  ; related to current installed version if detected and whether
  ; we are downgrading or not.
  ${If} $PassiveMode = 1
    Call PageLeaveReinstall
  ${Else}
    nsDialogs::Create 1018
    Pop $R4
    ${IfThen} $(^RTL) = 1 ${|} nsDialogs::SetRTL $(^RTL) ${|}

    ${NSD_CreateLabel} 0 0 100% 24u $R1
    Pop $R1

    ${NSD_CreateRadioButton} 30u 50u -30u 8u $R2
    Pop $R2
    ${NSD_OnClick} $R2 PageReinstallUpdateSelection

    ${NSD_CreateRadioButton} 30u 70u -30u 8u $R3
    Pop $R3
    ; Disable this radio button if downgrading and downgrades are disabled
    ${IfThen} $R0 = -1 ${|} EnableWindow $R3 0 ${|}
    ${NSD_OnClick} $R3 PageReinstallUpdateSelection

    ; Check the first radio button if this the first time
    ; we enter this page or if the second button wasn't
    ; selected the last time we were on this page
    ${If} $ReinstallPageCheck <> 2
      SendMessage $R2 ${BM_SETCHECK} ${BST_CHECKED} 0
    ${Else}
      SendMessage $R3 ${BM_SETCHECK} ${BST_CHECKED} 0
    ${EndIf}

    ${NSD_SetFocus} $R2
    nsDialogs::Show
  ${EndIf}
FunctionEnd
Function PageReinstallUpdateSelection
  ${NSD_GetState} $R2 $R1
  ${If} $R1 == ${BST_CHECKED}
    StrCpy $ReinstallPageCheck 1
  ${Else}
    StrCpy $ReinstallPageCheck 2
  ${EndIf}
FunctionEnd
Function PageLeaveReinstall
  ${NSD_GetState} $R2 $R1

  ; In update mode, always proceeds without uninstalling
  ${If} $UpdateMode = 1
    Goto reinst_done
  ${EndIf}

  ; $R0 holds whether same(0)/upgrading(1)/downgrading(-1) version
  ; $R1 holds the radio buttons state:
  ;   1 => first choice was selected
  ;   0 => second choice was selected
  ${If} $R0 = 0 ; Same version, proceed
    ${If} $R1 = 1              ; User chose to add/reinstall
      Goto reinst_done
    ${Else}                    ; User chose to uninstall
      Goto reinst_uninstall
    ${EndIf}
  ${ElseIf} $R0 = 1 ; Upgrading
    ${If} $R1 = 1              ; User chose to uninstall
      Goto reinst_uninstall
    ${Else}
      Goto reinst_done         ; User chose NOT to uninstall
    ${EndIf}
  ${ElseIf} $R0 = -1 ; Downgrading
    ${If} $R1 = 1              ; User chose to uninstall
      Goto reinst_uninstall
    ${Else}
      Goto reinst_done         ; User chose NOT to uninstall
    ${EndIf}
  ${EndIf}

  reinst_uninstall:
    HideWindow
    ClearErrors

    ; Not in the Tauri template: the uninstaller removes the login item of a program that is gone, but here the
    ; program is installed again right after, so the item is put back when the uninstall succeeded.
    ReadRegStr $SavedRunValue HKCU "${RUNKEY}" "${PRODUCTNAME}"
    ReadRegStr $4 HKCU "${MANUPRODUCTKEY}" ""
    ReadRegStr $R1 HKCU "${UNINSTKEY}" "UninstallString"
    ${IfThen} $UpdateMode = 1 ${|} StrCpy $R1 "$R1 /UPDATE" ${|} ; append /UPDATE
    ${IfThen} $PassiveMode = 1 ${|} StrCpy $R1 "$R1 /P" ${|} ; append /P
    StrCpy $R1 "$R1 _?=$4" ; append uninstall directory
    ExecWait '$R1' $0

    BringToFront

    ${IfThen} ${Errors} ${|} StrCpy $0 2 ${|} ; ExecWait failed, set fake exit code

    ${If} $0 <> 0
    ${OrIf} ${FileExists} "$INSTDIR\${MAINBINARYNAME}"
      ; User cancelled NSIS uninstaller? return to select un/reinstall page
      ${If} $0 = 1
        Abort
      ${EndIf}

      ; Other erros? show generic error message and return to select un/reinstall page
      MessageBox MB_ICONEXCLAMATION "$(unableToUninstall)"
      Abort
    ${EndIf}
    ${If} $SavedRunValue != ""
      WriteRegStr HKCU "${RUNKEY}" "${PRODUCTNAME}" $SavedRunValue
    ${EndIf}
  reinst_done:
FunctionEnd

Function SkipIfPassive
  ${IfThen} $PassiveMode = 1 ${|} Abort ${|}
FunctionEnd

Function RunMainBinary
  Exec '"$INSTDIR\${MAINBINARYNAME}"'
FunctionEnd

; The previous install location: the uninstall key written by the Tauri or this installer, then the manufacturer key.
Function RestorePreviousInstallLocation
  ReadRegStr $4 HKCU "${UNINSTKEY}" "InstallLocation"
  ${If} $4 != ""
    ; Tauri stores the path in double quotes.
    StrCpy $5 $4 1
    ${If} $5 == '"'
      StrLen $6 $4
      IntOp $6 $6 - 2
      StrCpy $4 $4 $6 1
    ${EndIf}
  ${Else}
    ReadRegStr $4 HKCU "${MANUPRODUCTKEY}" ""
  ${EndIf}
  ${If} $4 != ""
    StrCpy $INSTDIR $4
  ${EndIf}
FunctionEnd

Function .onInit
  ${GetOptions} $CMDLINE "/P" $PassiveMode
  ${IfNot} ${Errors}
    StrCpy $PassiveMode 1
  ${EndIf}
  ${GetOptions} $CMDLINE "/UPDATE" $UpdateMode
  ${IfNot} ${Errors}
    StrCpy $UpdateMode 1
  ${EndIf}
  ${If} $INSTDIR == "${PLACEHOLDER_INSTALL_DIR}"
    StrCpy $INSTDIR "$LOCALAPPDATA\${PRODUCTNAME}"
    Call RestorePreviousInstallLocation
  ${EndIf}
  ; A downgrade cannot be confirmed without a page: refuse it in silent and passive runs (Tauri: ALLOWDOWNGRADES
  ; false, its EarlyChecks refuse silent only). Interactively PageReinstall offers "uninstall before installing".
  ; SemverCompare gives 1 for an upgrade, 0 for the same version and -1 for a downgrade; an unreadable installed
  ; version is treated as older.
  ${If} ${Silent}
  ${OrIf} $PassiveMode = 1
    ReadRegStr $R1 HKCU "${UNINSTKEY}" "DisplayVersion"
    ${If} $R1 != ""
      nsis_tauri_utils::SemverCompare "${VERSION}" $R1
      Pop $R0
      ${If} $R0 = -1
        System::Call 'kernel32::AttachConsole(i -1)i.r0'
        ${If} $0 <> 0
          System::Call 'kernel32::GetStdHandle(i -11)i.r0'
          FileWrite $0 "A newer version of ${PRODUCTNAME} ($R1) is already installed; downgrades are not allowed.$\r$\n"
        ${EndIf}
        Abort
      ${EndIf}
    ${EndIf}
  ${EndIf}
FunctionEnd

Section "WebView2"
  ; The Wails window needs the WebView2 runtime. Skip when present, and on an update (it was there before).
  ${If} ${RunningX64}
    ReadRegStr $4 HKLM "SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\${WEBVIEW2APPGUID}" "pv"
  ${Else}
    ReadRegStr $4 HKLM "SOFTWARE\Microsoft\EdgeUpdate\Clients\${WEBVIEW2APPGUID}" "pv"
  ${EndIf}
  ${If} $4 == ""
    ReadRegStr $4 HKCU "SOFTWARE\Microsoft\EdgeUpdate\Clients\${WEBVIEW2APPGUID}" "pv"
  ${EndIf}
  ${If} $4 == ""
  ${AndIf} $UpdateMode <> 1
    Delete "$TEMP\MicrosoftEdgeWebview2Setup.exe"
    DetailPrint "Downloading the WebView2 bootstrapper..."
    NSISdl::download "https://go.microsoft.com/fwlink/p/?LinkId=2124703" "$TEMP\MicrosoftEdgeWebview2Setup.exe"
    Pop $0
    ${If} $0 != "success"
      Abort "Could not download the WebView2 runtime ($0). Install it from https://developer.microsoft.com/microsoft-edge/webview2/ and run this installer again."
    ${EndIf}
    ExecWait '"$TEMP\MicrosoftEdgeWebview2Setup.exe" /silent /install' $1
    ${If} $1 <> 0
      Abort "The WebView2 runtime installation failed ($1)."
    ${EndIf}
  ${EndIf}
SectionEnd

Section "Install"
  SetOutPath $INSTDIR
  ; Stops the running GUI first, then the daemon, and waits until its image is writable (shared with the Tauri
  ; installer, which has the same file lock problem).
  !insertmacro NSIS_HOOK_PREINSTALL
  File "/oname=${MAINBINARYNAME}" "${SRC_MAIN}"
  File "/oname=uniclipd.exe" "${SRC_DAEMON}"
  WriteUninstaller "$INSTDIR\uninstall.exe"

  WriteRegStr HKCU "${MANUPRODUCTKEY}" "" $INSTDIR
  WriteRegStr HKCU "${UNINSTKEY}" "MainBinaryName" "${MAINBINARYNAME}"
  WriteRegStr HKCU "${UNINSTKEY}" "DisplayName" "${PRODUCTNAME}"
  WriteRegStr HKCU "${UNINSTKEY}" "DisplayIcon" '"$INSTDIR\${MAINBINARYNAME}"'
  WriteRegStr HKCU "${UNINSTKEY}" "DisplayVersion" "${VERSION}"
  WriteRegStr HKCU "${UNINSTKEY}" "Publisher" "${MANUFACTURER}"
  WriteRegStr HKCU "${UNINSTKEY}" "InstallLocation" '"$INSTDIR"'
  WriteRegStr HKCU "${UNINSTKEY}" "UninstallString" '"$INSTDIR\uninstall.exe"'
  WriteRegDWORD HKCU "${UNINSTKEY}" "NoModify" 1
  WriteRegDWORD HKCU "${UNINSTKEY}" "NoRepair" 1

  CreateShortcut "$SMPROGRAMS\${PRODUCTNAME}.lnk" "$INSTDIR\${MAINBINARYNAME}"
  ; Passive and silent runs skip the finish page, so the desktop shortcut is created here.
  ${If} $PassiveMode = 1
  ${OrIf} ${Silent}
    CreateShortcut "$DESKTOP\${PRODUCTNAME}.lnk" "$INSTDIR\${MAINBINARYNAME}"
  ${EndIf}
  ${If} $PassiveMode = 1
    SetAutoClose true
  ${EndIf}
SectionEnd

; /R restarts the application with the arguments after /ARGS (an update from the running application).
Function .onInstSuccess
  ${If} $PassiveMode = 1
  ${OrIf} ${Silent}
    ${GetOptions} $CMDLINE "/R" $R0
    ${IfNot} ${Errors}
      ${GetOptions} $CMDLINE "/ARGS" $R0
      Exec '"$INSTDIR\${MAINBINARYNAME}" $R0'
    ${EndIf}
  ${EndIf}
FunctionEnd

Function un.SkipIfPassive
  ${IfThen} $PassiveMode = 1 ${|} Abort ${|}
FunctionEnd

Function un.ConfirmShow
  FindWindow $1 "#32770" "" $HWNDPARENT
  System::Call "user32::GetDpiForWindow(p r1) i .r2"
  ${If} $2 = 0
    StrCpy $2 96
  ${EndIf}
  IntOp $5 100 * $2
  IntOp $6 400 * $2
  IntOp $7 25 * $2
  IntOp $5 $5 / 96
  IntOp $6 $6 / 96
  IntOp $7 $7 / 96
  System::Call 'user32::CreateWindowEx(i ${__NSD_CheckBox_EXSTYLE}, w "${__NSD_CheckBox_CLASS}", w "Delete the application data", i ${__NSD_CheckBox_STYLE}, i 0, i r5, i r6, i r7, p r1, i0, i0, i0) i .s'
  Pop $DeleteAppDataCheckbox
  SendMessage $HWNDPARENT ${WM_GETFONT} 0 0 $1
  SendMessage $DeleteAppDataCheckbox ${WM_SETFONT} $1 1
FunctionEnd

Function un.ConfirmLeave
  SendMessage $DeleteAppDataCheckbox ${BM_GETCHECK} 0 0 $DeleteAppDataCheckboxState
FunctionEnd

Function un.onInit
  ${GetOptions} $CMDLINE "/P" $PassiveMode
  ${IfNot} ${Errors}
    StrCpy $PassiveMode 1
  ${EndIf}
  ${GetOptions} $CMDLINE "/UPDATE" $UpdateMode
  ${IfNot} ${Errors}
    StrCpy $UpdateMode 1
  ${EndIf}
FunctionEnd

Section "Uninstall"
  !insertmacro NSIS_HOOK_PREUNINSTALL
  Delete "$INSTDIR\${MAINBINARYNAME}"
  Delete "$INSTDIR\uniclipd.exe"
  Delete "$INSTDIR\uninstall.exe"
  RMDir "$INSTDIR"
  ${If} $UpdateMode <> 1
    Delete "$SMPROGRAMS\${PRODUCTNAME}.lnk"
    Delete "$DESKTOP\${PRODUCTNAME}.lnk"
    ; Do not leave a login item behind for a program that is gone (kept on updates).
    DeleteRegValue HKCU "${RUNKEY}" "${PRODUCTNAME}"
  ${EndIf}
  DeleteRegKey HKCU "${UNINSTKEY}"
  DeleteRegKey /ifempty HKCU "${MANUPRODUCTKEY}"
  ; The data the application keeps for itself (database, keys, caches: %LOCALAPPDATA%\<identifier>, and the WebView2
  ; profile under %APPDATA%) is only removed when asked for, never on an update (Tauri template behavior).
  ${If} $DeleteAppDataCheckboxState = 1
  ${AndIf} $UpdateMode <> 1
    DeleteRegKey /ifempty HKCU "Software\${MANUFACTURER}"
    SetShellVarContext current
    RmDir /r "$APPDATA\${BUNDLEID}"
    RmDir /r "$LOCALAPPDATA\${BUNDLEID}"
  ${EndIf}
  ${If} $PassiveMode = 1
  ${OrIf} $UpdateMode = 1
    SetAutoClose true
  ${EndIf}
SectionEnd
