// Generated by apps/gui-go/cmd/hostcontract from apps/gui-go/internal/hostapi (the error catalog). Do not edit.
//
// Wails generates the command signatures and DTOs (apps/gui-go/frontend/bindings), but a bound Go method only
// returns `error`, so the framework cannot describe which codes a command rejects with. The catalog in Go is the
// single source of those codes and of their severity; this file is its TypeScript form.
//
// User-facing rejections are normal product flow (wrong passphrase, cancelled dialog, bad input) and are never
// reported to Sentry. A token that is not listed is treated as a system error (fail safe toward visibility).

export const COMMAND_ERROR_CODES = ['NotFound', 'InternalError', 'Timeout', 'Cancelled', 'ValidationError', 'Conflict', 'AccessibilityPermissionRequired'] as const
export type CommandErrorCode = (typeof COMMAND_ERROR_CODES)[number]
/** Rejection of most commands. */
export type CommandError = { code: CommandErrorCode; message: string }

export const UNLOCK_ERROR_CODES = ['WRONG_PASSPHRASE', 'CORRUPTED_KEY_MATERIAL', 'SETUP_NOT_COMPLETED', 'SPACE_NOT_INITIALIZED', 'PROFILE_RECOVERY_REQUIRED', 'PROFILE_RECOVERY_PARTIAL', 'PROFILE_RECOVERY_UNSUPPORTED', 'PROFILE_RECOVERY_PERSISTENCE_FAILED', 'INTERNAL'] as const
export type ContentUnlockErrorCode = (typeof UNLOCK_ERROR_CODES)[number]
/** Rejection of unlock_content: only the stable code crosses the bridge. */
export type ContentUnlockError = { code: ContentUnlockErrorCode }

export const CONFIG_ERROR_KINDS = ['cancelled', 'daemon', 'internal'] as const
export type ConfigCommandErrorKind = (typeof CONFIG_ERROR_KINDS)[number]
/** Rejection of the config package commands, told apart by `kind`. */
export type ConfigCommandError =
  | { kind: 'cancelled' }
  | { kind: 'daemon'; status: number; code: string | null; message: string }
  | { kind: 'internal'; message: string }

/** Update, quick panel and window commands reject with a plain string and have no code. */
export type TextCommandError = string

export const USER_FACING_ERROR_CODES: ReadonlySet<string> = new Set([
  'NotFound',
  'Cancelled',
  'ValidationError',
  'Conflict',
  'AccessibilityPermissionRequired',
  'WRONG_PASSPHRASE',
  'SETUP_NOT_COMPLETED',
  'SPACE_NOT_INITIALIZED',
  'PROFILE_RECOVERY_REQUIRED',
])

export const USER_FACING_ERROR_KINDS: ReadonlySet<string> = new Set([
  'cancelled',
])
