// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../encoding/json/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BeginVisualEffectsSample asks for permission to measure one sample. This host does not sample frames, so no
 * permit is ever granted (always nil).
 */
export function BeginVisualEffectsSample(sessionID: string): $CancellablePromise<$models.SamplePermit | null> {
    return $Call.ByID(4266959612, sessionID);
}

/**
 * CancelDownload cancels a running download. It does nothing when none is active.
 */
export function CancelDownload(): $CancellablePromise<void> {
    return $Call.ByID(3435788457);
}

/**
 * CheckForUpdate looks for a newer release on the given channel (null = the user's channel) and tells every window
 * through `update-available`. It resolves nil when the app is up to date.
 */
export function CheckForUpdate(channel: string | null): $CancellablePromise<$models.UpdateMetadata | null> {
    return $Call.ByID(975432833, channel);
}

/**
 * DevOpenUpdaterWindow opens the update window in preview mode (`?dev=1`), which shows a sample release. It is a
 * development aid of the settings page; the window itself decides what the flag shows.
 */
export function DevOpenUpdaterWindow(): $CancellablePromise<void> {
    return $Call.ByID(3318247051);
}

/**
 * DismissQuickPanel hides the quick panel and gives the focus back to the application that had it.
 */
export function DismissQuickPanel(): $CancellablePromise<void> {
    return $Call.ByID(3797915006);
}

/**
 * DownloadUpdate downloads the pending release in the background; progress is broadcast on
 * `update-download-progress`. It resolves when the download finished and rejects on failure or cancellation.
 */
export function DownloadUpdate(): $CancellablePromise<void> {
    return $Call.ByID(3671538134);
}

/**
 * ExportConfigPackage asks where to save, then has the daemon write the configuration bundle there.
 */
export function ExportConfigPackage(): $CancellablePromise<$models.ExportConfigResult> {
    return $Call.ByID(191861177);
}

/**
 * ExportStartupLogs zips the logs to a place the user picks. It resolves nil when the user cancels.
 */
export function ExportStartupLogs(): $CancellablePromise<string | null> {
    return $Call.ByID(1074859333);
}

/**
 * FinalizeQuickPanelShow is the second phase of showing the panel, after the page cleared its stale state.
 */
export function FinalizeQuickPanelShow(): $CancellablePromise<void> {
    return $Call.ByID(1474266219);
}

/**
 * GetAutoDownloadUpdate reads the "download updates automatically" setting.
 */
export function GetAutoDownloadUpdate(): $CancellablePromise<boolean> {
    return $Call.ByID(3752535471);
}

/**
 * GetContentUnlocked reports whether the daemon lets this GUI show content right now.
 */
export function GetContentUnlocked(): $CancellablePromise<boolean> {
    return $Call.ByID(2578330567);
}

/**
 * GetDaemonBootstrapFailure reports why the daemon bootstrap failed. It is always nil in this host: a bootstrap
 * failure ends the process with a native dialog (see HostService.fatal), so no page is left to ask.
 */
export function GetDaemonBootstrapFailure(): $CancellablePromise<$models.DaemonBootstrapFailure | null> {
    return $Call.ByID(2237748181);
}

/**
 * GetDaemonConnectionInfo tells the page where the daemon listens. It is nil until the daemon bootstrap finished.
 */
export function GetDaemonConnectionInfo(): $CancellablePromise<$models.DaemonConnection | null> {
    return $Call.ByID(3594356777);
}

/**
 * GetDaemonSession exchanges a short-lived daemon session for the page. It is nil until the daemon bootstrap
 * finished.
 */
export function GetDaemonSession(): $CancellablePromise<$models.DaemonSession | null> {
    return $Call.ByID(1101395823);
}

/**
 * GetDaemonStartupStatus returns the daemon's startup progress (`GET /startup`) as the daemon sent it: nil while
 * the daemon is not reachable yet. The payload is owned by the daemon contract (crates/uc-daemon-contract startup.rs),
 * which the OpenAPI document does not export, so the host passes it through untouched and the page declares its shape.
 */
export function GetDaemonStartupStatus(): $CancellablePromise<json$0.RawMessage> {
    return $Call.ByID(2849288988);
}

/**
 * GetDesktopTheme reports the desktop theme. Only a Linux host with an Omarchy theme source could report one; this
 * host has none on any platform, so it always answers "unavailable" and `desktop-theme://changed` is never sent.
 */
export function GetDesktopTheme(): $CancellablePromise<$models.DesktopThemeSnapshot> {
    return $Call.ByID(567851396);
}

/**
 * GetDeviceID returns this device's peer id.
 */
export function GetDeviceID(): $CancellablePromise<string> {
    return $Call.ByID(1602021334);
}

/**
 * GetDeviceMeta returns the host's device and application metadata for the page's Sentry scope.
 */
export function GetDeviceMeta(): $CancellablePromise<$models.DeviceMeta> {
    return $Call.ByID(2021800294);
}

/**
 * GetDownloadProgress returns the pending update state, so a window that mounts mid-download can catch up before it
 * listens to the broadcast events.
 */
export function GetDownloadProgress(): $CancellablePromise<$models.DownloadProgressSnapshot> {
    return $Call.ByID(2087922714);
}

/**
 * GetInstallKind tells how this copy was installed, so the page can route package-managed copies to their package
 * manager instead of the in-app updater.
 */
export function GetInstallKind(): $CancellablePromise<$models.InstallKind> {
    return $Call.ByID(3042716058);
}

/**
 * GetProfileRecovery returns the daemon's profile recovery state (`GET /encryption/recovery`) untouched. Its shape
 * is the daemon's `ProfileRecoveryResponse`, which the page takes from the generated OpenAPI client.
 */
export function GetProfileRecovery(): $CancellablePromise<json$0.RawMessage> {
    return $Call.ByID(232979809);
}

/**
 * GetQuickPanelDoubleTapAvailability tells whether the modifier double tap trigger can work in this session.
 */
export function GetQuickPanelDoubleTapAvailability(): $CancellablePromise<$models.ModifierDoubleTapAvailability> {
    return $Call.ByID(1750704259);
}

/**
 * GetVisualEffects returns the visual effects state of this session.
 */
export function GetVisualEffects(): $CancellablePromise<$models.EffectsSnapshot> {
    return $Call.ByID(1553539489);
}

/**
 * HostNotificationPermission reports whether system notifications are allowed. It is an adapter command of the
 * page's notification plugin import (frontend/src/host/notification.ts), not part of the Tauri command set.
 */
export function HostNotificationPermission(): $CancellablePromise<boolean> {
    return $Call.ByID(4161242273);
}

/**
 * HostNotificationRequestPermission asks the system for notification permission (adapter command).
 */
export function HostNotificationRequestPermission(): $CancellablePromise<$models.NotificationPermission> {
    return $Call.ByID(3817032772);
}

/**
 * HostNotificationSend shows a system notification (adapter command). A stable ID replaces an earlier
 * notification of the same kind.
 */
export function HostNotificationSend(options: $models.HostNotification): $CancellablePromise<void> {
    return $Call.ByID(1431177108, options);
}

/**
 * ImportConfigPackage validates a bundle and stages it to be applied at the next start.
 */
export function ImportConfigPackage(password: string, sourcePath: string): $CancellablePromise<$models.ImportConfigStageResult> {
    return $Call.ByID(2573355644, password, sourcePath);
}

/**
 * InstallUpdate downloads (if needed) and installs the pending release, then relaunches or quits as the platform's
 * installer requires. Its progress is sent on `update-install-progress`, which only this call produces.
 */
export function InstallUpdate(): $CancellablePromise<void> {
    return $Call.ByID(4202083003);
}

/**
 * MainWindowPresentationReady is the page's handshake that the main window finished its first paint. The Go host
 * shows the window itself and has a single window generation, so there is nothing to reconcile: it is inert.
 */
export function MainWindowPresentationReady(generation: string): $CancellablePromise<void> {
    return $Call.ByID(4277926449, generation);
}

/**
 * MarkMainWindowReady is the page's handshake that the main window is ready to be shown. Inert for the same reason.
 */
export function MarkMainWindowReady(generation: string): $CancellablePromise<void> {
    return $Call.ByID(3012737918, generation);
}

/**
 * MarkQuickPanelReady tells the host the panel page finished loading; a toggle requested earlier then takes effect.
 */
export function MarkQuickPanelReady(): $CancellablePromise<void> {
    return $Call.ByID(996318160);
}

/**
 * OpenDataDirectory reveals the application data folder in the file manager.
 */
export function OpenDataDirectory(): $CancellablePromise<void> {
    return $Call.ByID(567735070);
}

/**
 * OpenImageExternally hands image bytes to the system viewer through a single scratch file that is replaced on
 * every call. The bytes cross the bridge as a base64 string.
 */
export function OpenImageExternally(fileName: string, data: string | null): $CancellablePromise<void> {
    return $Call.ByID(1108686220, fileName, data);
}

/**
 * OpenLogsDirectory opens the log folder in the file manager, creating it first.
 */
export function OpenLogsDirectory(): $CancellablePromise<void> {
    return $Call.ByID(1661929119);
}

/**
 * OpenURL opens a link in the default browser. It is an adapter command of the page's opener plugin import
 * (frontend/src/host/opener.ts), not part of the Tauri command set.
 */
export function OpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(796564632, url);
}

/**
 * OpenUpdaterWindow opens the software update window, or focuses it when it is already open.
 */
export function OpenUpdaterWindow(): $CancellablePromise<void> {
    return $Call.ByID(1832309800);
}

/**
 * PasteToPreviousApp hides the panel, returns to the previously focused application and pastes. It rejects with a
 * plain string (hostapi.TextError); the panel is shown again on failure so the selection is not lost.
 */
export function PasteToPreviousApp(): $CancellablePromise<void> {
    return $Call.ByID(2482598637);
}

/**
 * PickConfigBundlePath shows the native open dialog for a configuration bundle. It resolves nil when cancelled.
 */
export function PickConfigBundlePath(): $CancellablePromise<string | null> {
    return $Call.ByID(2791586351);
}

/**
 * PickDirectory shows the native folder picker. It resolves nil when the user cancels.
 */
export function PickDirectory(): $CancellablePromise<string | null> {
    return $Call.ByID(1045546125);
}

/**
 * PreviewConfigImport reads the descriptive metadata of a bundle without importing it.
 */
export function PreviewConfigImport(password: string, sourcePath: string): $CancellablePromise<$models.ConfigImportPreview> {
    return $Call.ByID(1093641094, password, sourcePath);
}

/**
 * QuickPanelUsesCompositorShortcuts reports whether the shortcut is bound by the Wayland compositor instead of the app.
 */
export function QuickPanelUsesCompositorShortcuts(): $CancellablePromise<boolean> {
    return $Call.ByID(1334979728);
}

/**
 * ReportVisualEffectsEnvironment records the system reduce-motion preference the page observed.
 */
export function ReportVisualEffectsEnvironment(sessionID: string, systemMotion: $models.SystemMotion): $CancellablePromise<$models.EffectsSnapshot> {
    return $Call.ByID(2881188950, sessionID, systemMotion);
}

/**
 * ReportVisualEffectsSample accepts a frame-timing sample. It is read and dropped: this host does not sample.
 */
export function ReportVisualEffectsSample(sample: $models.EffectsSample): $CancellablePromise<$models.EffectsSnapshot> {
    return $Call.ByID(1922281659, sample);
}

/**
 * ResolveQuickPanelExpandSide tells which side the inline preview opens toward. This host always opens to the right.
 */
export function ResolveQuickPanelExpandSide(scale: number | null): $CancellablePromise<$models.QuickPanelExpandSide> {
    return $Call.ByID(3369126533, scale);
}

/**
 * RestartApp restarts the daemon and then the GUI.
 */
export function RestartApp(): $CancellablePromise<void> {
    return $Call.ByID(3159761641);
}

/**
 * RestartDaemon replaces the daemon process; the page reconnects itself.
 */
export function RestartDaemon(): $CancellablePromise<void> {
    return $Call.ByID(3085017198);
}

/**
 * RevealPath shows an existing file or folder in the file manager.
 */
export function RevealPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(431717549, path);
}

/**
 * SaveImageAs writes image bytes to a place the user picks. It resolves nil when the user cancels. The bytes cross
 * the bridge as a base64 string (Go []byte), not as a number array.
 */
export function SaveImageAs(fileName: string, data: string | null): $CancellablePromise<string | null> {
    return $Call.ByID(1087714767, fileName, data);
}

/**
 * SetAutoDownloadUpdate saves the "download updates automatically" setting.
 */
export function SetAutoDownloadUpdate(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(291500547, enabled);
}

/**
 * SetFollowOmarchyTheme would switch the page to the Omarchy theme. Unsupported: with no theme source the request
 * changes nothing and the answer stays "unavailable".
 */
export function SetFollowOmarchyTheme(enabled: boolean): $CancellablePromise<$models.DesktopThemeSnapshot> {
    return $Call.ByID(117402040, enabled);
}

/**
 * SetQuickPanelDoubleTapModifier sets the modifier whose double tap opens the quick panel.
 */
export function SetQuickPanelDoubleTapModifier(modifier: $models.QuickPanelDoubleTapModifier): $CancellablePromise<void> {
    return $Call.ByID(2493414205, modifier);
}

/**
 * SetQuickPanelEnabled turns the quick panel and its global shortcut on or off.
 */
export function SetQuickPanelEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1363624867, enabled);
}

/**
 * SetQuickPanelLayout sizes the quick panel for the page's content scale, the preview pane and (Linux) the window
 * scale. A null scale means 1.
 */
export function SetQuickPanelLayout(scale: number | null, previewExpanded: boolean, windowScale: number | null): $CancellablePromise<void> {
    return $Call.ByID(2365325168, scale, previewExpanded, windowScale);
}

/**
 * SetQuickPanelPosition saves where the quick panel appears.
 */
export function SetQuickPanelPosition(position: $models.QuickPanelPosition): $CancellablePromise<void> {
    return $Call.ByID(2788891745, position);
}

/**
 * SetTrafficLightPosition would place the macOS window buttons. Inert: Wails draws them with the hidden-inset title
 * bar at a fixed place, and the page's offset is not applied.
 */
export function SetTrafficLightPosition(offsetX: number | null, offsetY: number | null): $CancellablePromise<void> {
    return $Call.ByID(4096480177, offsetX, offsetY);
}

/**
 * SetTrayLanguage updates the tray menu labels to the UI language. It does not persist anything.
 */
export function SetTrayLanguage(language: string): $CancellablePromise<void> {
    return $Call.ByID(4127180375, language);
}

/**
 * SetVisualEffectsMode sets the visual effects preference and tells every window.
 */
export function SetVisualEffectsMode(mode: $models.EffectsMode): $CancellablePromise<$models.EffectsSnapshot> {
    return $Call.ByID(1102935882, mode);
}

/**
 * SetWindowDecorations applies the page's frame preference (custom controls drawn by the page, or the system
 * frame) to the main window. macOS keeps its hidden-inset title bar either way.
 */
export function SetWindowDecorations(decorations: boolean): $CancellablePromise<void> {
    return $Call.ByID(1382029332, decorations);
}

/**
 * ShowContentUnlock brings the main window forward so the user can unlock content.
 */
export function ShowContentUnlock(): $CancellablePromise<void> {
    return $Call.ByID(1835680799);
}

/**
 * SkipVersion remembers that the user does not want the given version on the current channel.
 */
export function SkipVersion(version: string): $CancellablePromise<void> {
    return $Call.ByID(3059599220, version);
}

/**
 * TakePendingNavigation returns, once, the route a tray or second launch asked the page to open.
 */
export function TakePendingNavigation(): $CancellablePromise<string | null> {
    return $Call.ByID(1767658493);
}

/**
 * TypeFilePathsToPreviousApp types file paths, one per line, into the previously focused application.
 */
export function TypeFilePathsToPreviousApp(request: $models.FilePathInputRequest): $CancellablePromise<void> {
    return $Call.ByID(2683213434, request);
}

/**
 * UnlockContent unlocks content with the user's passphrase. It rejects with a hostapi.UnlockError: only the stable
 * code crosses the bridge, because the daemon's text may contain private data.
 */
export function UnlockContent(request: $models.ContentUnlockRequest): $CancellablePromise<void> {
    return $Call.ByID(1868356668, request);
}

/**
 * UnlockContentFromKeyring unlocks content with the key kept in the system keychain. It resolves false when the
 * user refused the keychain prompt or the keychain had no usable key: the page then shows the passphrase form.
 */
export function UnlockContentFromKeyring(): $CancellablePromise<boolean> {
    return $Call.ByID(266640757);
}

/**
 * UpdateAutostart registers or removes the login item and stores the preference. The preference is saved first and
 * put back if the operating system refuses the registration.
 */
export function UpdateAutostart(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1965524327, enabled);
}

/**
 * UpdateKeyboardShortcuts merges a shortcut patch into the settings and re-binds the global shortcut. A null value
 * clears the shortcut; any other value is one accelerator string or a list of alternatives (opaque JSON here, see
 * UpdateKeyboardShortcutsResult).
 */
export function UpdateKeyboardShortcuts(shortcuts: { [_ in string]?: json$0.RawMessage } | null): $CancellablePromise<$models.UpdateKeyboardShortcutsResult> {
    return $Call.ByID(2571342418, shortcuts);
}
