// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as daemonclient$0 from "../../packages/desktop-host-go/daemonclient/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Connection(): $CancellablePromise<$models.Connection> {
    return $Call.ByID(2277116259);
}

/**
 * GetContentUnlocked reports whether the daemon lets this GUI show content right now.
 */
export function GetContentUnlocked(): $CancellablePromise<boolean> {
    return $Call.ByID(2578330567);
}

/**
 * Invoke executes one host command on behalf of the shared React frontend.
 */
export function Invoke(name: string, args: { [_ in string]?: json$0.RawMessage } | null): $CancellablePromise<$models.InvokeResult> {
    return $Call.ByID(3222992067, name, args);
}

export function Session(): $CancellablePromise<daemonclient$0.Session> {
    return $Call.ByID(3789700637);
}

/**
 * UnlockContent unlocks content with the user's passphrase. It rejects with a hostapi.UnlockError: only the stable
 * code crosses the bridge, because the daemon's text may contain private data.
 */
export function UnlockContent(request: $models.ContentUnlockRequest): $CancellablePromise<void> {
    return $Call.ByID(1868356668, request);
}
