// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../encoding/json/models.js";

/**
 * AutoResult is what the automatic mode resolved to.
 */
export enum AutoResult {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AutoResultEffects = "effects",
    AutoResultSmooth = "smooth",
};

/**
 * ConfigImportPreview is the descriptive, non-secret metadata of a configuration bundle.
 */
export interface ConfigImportPreview {
    "appVersion": string;
    "sourceMode": string;
    "createdAtUnixMs": number;
    "profileId": string;
    "deviceFingerprint": string;
}

/**
 * ContentUnlockRequest is the passphrase submitted to unlock content.
 */
export interface ContentUnlockRequest {
    "passphrase": string;
}

/**
 * DaemonBootstrapFailure is the machine-readable reason the daemon bootstrap failed.
 */
export interface DaemonBootstrapFailure {
    "kind": DaemonBootstrapFailureKind;
    "detail": string;
    "observedVersion": string | null;
    "expectedVersion": string | null;
}

/**
 * DaemonBootstrapFailureKind classifies why the host could not attach to a daemon.
 */
export enum DaemonBootstrapFailureKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * BootstrapFailureVersionTooOld means a newer daemon than this GUI is running: the fix is to update the app.
     */
    BootstrapFailureVersionTooOld = "versionTooOld",

    /**
     * BootstrapFailureUnavailable is any other terminal bootstrap failure.
     */
    BootstrapFailureUnavailable = "unavailable",
};

/**
 * DaemonConnection is where the frontend reaches the daemon.
 */
export interface DaemonConnection {
    "baseUrl": string;
    "wsUrl": string;
}

/**
 * DaemonSession is a short-lived daemon session credential for the webview.
 */
export interface DaemonSession {
    "sessionToken": string;
    "expiresInSecs": number;
    "refreshAtSecs": number;
}

/**
 * DesktopTheme is a desktop-provided colour theme.
 */
export interface DesktopTheme {
    "dark": boolean;
    "variables": { [_ in string]?: string } | null;
}

/**
 * DesktopThemeSnapshot is the desktop theme state; only Linux hosts with an Omarchy theme source report it available.
 */
export interface DesktopThemeSnapshot {
    "revision": number;
    "followOmarchyTheme": boolean;
    "omarchyAvailable": boolean;
    "theme": DesktopTheme | null;
    "windowCornerRadius": number | null;
}

/**
 * DeviceMeta is the host's device and application metadata, used to complete the frontend's Sentry scope.
 */
export interface DeviceMeta {
    "deviceId": string;
    "deviceRole": string;
    "platform": string;
    "appVersion": string;
    "appChannel": string;
    "runtimeProfile": string;
    "developmentMode": boolean;
}

/**
 * DownloadEvent is one step of an update download or install. Wails has no tagged unions, so the payload of each
 * kind is a flat optional field: Started carries ContentLength (absent when the size is unknown), Progress carries
 * ChunkLength, Failed carries Error, Finished carries none.
 */
export interface DownloadEvent {
    "event": DownloadEventKind;
    "data"?: DownloadEventData | null;
}

/**
 * DownloadEventData holds the fields of a DownloadEvent; which one is set depends on the kind.
 */
export interface DownloadEventData {
    "contentLength"?: number | null;
    "chunkLength"?: number | null;
    "error"?: string | null;
}

/**
 * DownloadEventKind tells the stage of an update download.
 */
export enum DownloadEventKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DownloadEventStarted = "Started",
    DownloadEventProgress = "Progress",
    DownloadEventFinished = "Finished",
    DownloadEventFailed = "Failed",
};

/**
 * DownloadPhase is the coarse state of the pending update.
 */
export enum DownloadPhase {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DownloadPhaseIdle = "idle",
    DownloadPhaseAvailable = "available",
    DownloadPhaseDownloading = "downloading",
    DownloadPhaseReady = "ready",
};

/**
 * DownloadProgressSnapshot is the queryable download state, so a window that mounts mid-download can catch up.
 */
export interface DownloadProgressSnapshot {
    "phase": DownloadPhase;
    "downloaded": number;
    "total": number | null;
    "version": string | null;
    "currentVersion": string;
    "body": string | null;
    "date": string | null;
}

/**
 * EffectsMode is the user's visual effects preference.
 */
export enum EffectsMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    EffectsModeAuto = "auto",
    EffectsModeEffects = "effects",
    EffectsModeSmooth = "smooth",
};

/**
 * EffectsPersistence says whether the preference survives a restart.
 */
export enum EffectsPersistence {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    EffectsPersistenceSaved = "saved",
    EffectsPersistenceSessionOnly = "session_only",
};

/**
 * EffectsReason says why the effective mode is what it is.
 */
export enum EffectsReason {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    EffectsReasonManual = "manual",
    EffectsReasonSystem = "system",
    EffectsReasonPlatformDefault = "platform_default",
    EffectsReasonHardware = "hardware",
    EffectsReasonUnknown = "unknown",
    EffectsReasonRuntime = "runtime",
};

/**
 * EffectsSample is one frame-timing sample reported by the page.
 */
export interface EffectsSample {
    "sessionId": string;
    "sampleId": number;
    "revision": number;
    "frames": number;
    "durationMs": number | null;
    "longFrames": number;
    "longestMs": number | null;
}

/**
 * EffectsSnapshot is the visual effects state of the running session.
 */
export interface EffectsSnapshot {
    "sessionId": string;
    "revision": number;
    "mode": EffectsMode;
    "autoForSession": AutoResult;
    "nextAuto": AutoResult | null;
    "systemMotion": SystemMotion;
    "reduceMotion": boolean;
    "lowEffects": boolean;
    "reason": EffectsReason;
    "persistence": EffectsPersistence;
}

/**
 * ExportConfigResult is the outcome of a configuration package export.
 */
export interface ExportConfigResult {
    /**
     * Path is the absolute path the bundle was written to.
     */
    "path": string;
}

/**
 * FilePathInputRequest holds file paths to type into the application that was focused before the panel opened.
 */
export interface FilePathInputRequest {
    "filePaths": string[] | null;
}

/**
 * HostNotification is a notification to show; a stable ID replaces an earlier notification of the same kind.
 */
export interface HostNotification {
    "id": number | null;
    "title": string;
    "body": string;
}

/**
 * ImportConfigStageResult is the outcome of staging a configuration bundle for the next start.
 */
export interface ImportConfigStageResult {
    /**
     * StagedOK is true on success: the bundle was validated and staged.
     */
    "stagedOk": boolean;

    /**
     * UnlockRequiredAfterApply is true when applying the staged migration requires the passphrase again.
     */
    "unlockRequiredAfterApply": boolean;
}

/**
 * InstallKind is how the running copy was installed.
 */
export enum InstallKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    InstallKindMacOS = "macos",
    InstallKindWindows = "windows",
    InstallKindWindowsPortable = "windowsportable",
    InstallKindAppImage = "appimage",
    InstallKindDeb = "deb",
    InstallKindRPM = "rpm",
    InstallKindUnknown = "unknown",
};

/**
 * ModifierDoubleTapAvailability says whether the modifier double tap trigger can work in this session.
 */
export enum ModifierDoubleTapAvailability {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DoubleTapSupported = "supported",
    DoubleTapAccessibilityPermissionNeeded = "accessibility_permission_required",
    DoubleTapUnsupportedDisplaySession = "unsupported_display_session",
};

/**
 * NotificationAction is delivered when the user clicks a notification, in the shape the plugin's handler receives.
 */
export interface NotificationAction {
    "id"?: number | null;
}

/**
 * NotificationPermission is the notification permission state the adapter reports.
 */
export enum NotificationPermission {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    NotificationGranted = "granted",
    NotificationDenied = "denied",
};

/**
 * QuickPanelDoubleTapModifier is the modifier whose double tap opens the quick panel.
 */
export enum QuickPanelDoubleTapModifier {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DoubleTapModifierDisabled = "disabled",
    DoubleTapModifierAlt = "alt",
    DoubleTapModifierControl = "control",
    DoubleTapModifierMeta = "meta",
};

/**
 * QuickPanelExpandSide is the side the inline preview opens toward.
 */
export enum QuickPanelExpandSide {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ExpandSideRight = "right",
    ExpandSideLeft = "left",
};

/**
 * QuickPanelPosition is where the quick panel appears.
 */
export enum QuickPanelPosition {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    QuickPanelPositionCenter = "center",
    QuickPanelPositionFollowCursor = "follow_cursor",
};

/**
 * SamplePermit allows the page to measure one sample.
 */
export interface SamplePermit {
    "sampleId": number;
    "revision": number;
    "sessionId": string;
}

/**
 * SettingsChanged is what the page sends after saving settings; the tray reads the sync switch out of the JSON.
 */
export interface SettingsChanged {
    "settingJson": string;
    "timestamp": number;
}

/**
 * SystemMotion is the operating system's reduce-motion preference as the page reports it.
 */
export enum SystemMotion {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SystemMotionReduce = "reduce",
    SystemMotionAllow = "allow",
    SystemMotionUnknown = "unknown",
};

/**
 * UpdateKeyboardShortcutsResult is the merged shortcut table after an update. A value is one accelerator string or a
 * list of alternatives; Wails cannot express that union, so the value is opaque JSON here and the frontend narrows
 * it with the daemon's `ShortcutKeyDto`.
 */
export interface UpdateKeyboardShortcutsResult {
    "keyboardShortcuts": { [_ in string]?: json$0.RawMessage } | null;
}

/**
 * UpdateMetadata describes an available update.
 */
export interface UpdateMetadata {
    "version": string;
    "currentVersion": string;
    "body": string | null;
    "date": string | null;
}
