// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Connection {
    "baseUrl": string;
    "wsUrl": string;
    "profile": string;
    "pid": number;
}

/**
 * ContentUnlockRequest is the passphrase submitted to unlock content.
 */
export interface ContentUnlockRequest {
    "passphrase": string;
}

/**
 * InvokeResult is the envelope returned to the WebView. The frontend adapter
 * rethrows Error unchanged so typed command errors keep their Tauri shape.
 */
export interface InvokeResult {
    "ok": boolean;
    "data"?: any;
    "error"?: any;
}
